### PR TITLE
Fix rule var paths

### PR DESCRIPTION
**Pull request by starkos**
Correct rule variables containing paths for Visual Studio by translating and making relative to the project.

### CODE REVIEW

**Comment by TurkeyMan** [comment]
I kinda wonder if this function could also do substitutions for the builtin variables, ie $(SolutionDir), $(ProjectDir), $(TargetDir), etc?
Any paths that are recognised to be relative to those locations for which there are variables, we could substitute with the proper variables. That would make VS project generation far more natural.

**Comment by TurkeyMan** [comment]
Anyway, this looks good, that was just something to think on.

**Comment by tvandijck** [comment]
> I kinda wonder if this function could also do substitutions for the builtin variables

That would really only be useful if you generate your solution and projects in place though.... in our case we have the build output going into a different folder, for some people even on an entirely different drive (RAMDISK orso)... $(ProjectDir) at that point becomes rather pointless to use.

**Comment by TurkeyMan** [comment]
But in that case, the substitutions wouldn't happen, in that they wouldn't be relative to those variables...
I suggest only if the absolute paths ARE relative to those variables that they should substitute as I think most VS users would expect/prefer.

**Comment by starkos** [comment]
> I kinda wonder if this function could also do substitutions for the builtin variables, ie $(SolutionDir), $(ProjectDir), $(TargetDir), etc?

In theory yes, but it probably makes more sense to do it during or after expanding the tokens instead, to be generic across exporters. The detoken code can already map specific tokens to toolset specific variables (search for "pathVar").

**Pull request merged**
