### PR TITLE
Remove unused configuration from gmake2

### PR DESCRIPTION
**Pull request by cathei**
**What does this PR do?**

Remove `env.PathVars` (notice the capitalization) that had no effect.

**How does this PR change Premake's behavior?**

Shouldn't change any behavior as it has wrong name and not referenced.

**Anything else we should know?**

N/A

**Did you check all the boxes?**

- [x] Focus on a single fix or feature; remove any unrelated formatting or code changes
- [x] Add unit tests showing fix or feature works; all tests pass
- [x] Mention any [related issues](https://github.com/premake/premake-core/issues) (put `closes #XXXX` in comment to auto-close issue when PR is merged)
- [x] Follow our [coding conventions](https://github.com/premake/premake-core/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] Minimize the number of commits
- [x] Align [documentation](https://github.com/premake/premake-core/tree/master/website) to your changes

*You can now [support Premake on our OpenCollective](https://opencollective.com/premake). Your contributions help us spend more time responding to requests like these!*

### CODE REVIEW

**Comment by nickclark2016** [comment]
Any reason to remove this, rather than rename is properly to `pathVars`?

**Comment by cathei** [comment]
> Any reason to remove this, rather than rename is properly to `pathVars`?

This was my thought process:
* If the values are identical to tokens from fileconfig, then there would be no point of re-defining here.
* If the values are not identical, then it might break existing scripts that use tokens, due to behavior change.

**Comment by Jarod42** [comment]
As I remember, it might be useful only for cases with `absolute = true` (as other values are identical as without pathvars)...

But I would say our handling of absolute is strange anyway (we have `%{!path}` to turn/keep absolute path, `%{absolute_path_token}` might turn into relative path (inside `%[path]`)).

Created [project-tokens](https://github.com/Jarod42/premake-sample-projects/tree/project-tokens/projects/project-tokens) to test tokens.

**Review by nickclark2016 — APPROVED** [review]

**Comment by nickclark2016** [comment]
@cathei do you mind pushing up an empty commit to retrigger actions? Once they're triggered and pass I should be able to merge this.

**Comment by nickclark2016** [comment]
Poking on this to see if we can get a commit to retrigger the workflow @cathei

**Comment by cathei** [comment]
@nickclark2016 Sorry for the delay, done now :)

**Review by Jarod42 — APPROVED** [review]

**Pull request merged**
