### PR TITLE
Fix path normalization for URLs

### PR DESCRIPTION
**Pull request by nmoehrle**
This is a possible solution for #537

### CODE REVIEW

**Comment by samsinsane** [comment]
I don't think this is the correct solution to the problem, look into #320 for the preferred solution. It needs some fixes, but it's pretty much good to go.

**Comment by tvandijck** [comment]
@samsinsane if this is not the right fix, should we close it?

**Comment by samsinsane** [comment]
Potentially, it depends on whether @nmoehrle wants to fix this up or not.

**Comment by nmoehrle** [comment]
Sorry for the mess I am in the process of cleaning it up...

**Pull request closed without merging**
