### PR TITLE
Add projects web and github

### PR DESCRIPTION
**Pull request by Jarod42**
**What does this PR do?**

Add project Web and github to see content of those directory in solution.

**How does this PR change Premake's behavior?**

No changes

**Anything else we should know?**

Alternative would be to place the files directly inside Premake's project.
No real preferences on my side.

**Did you check all the boxes?**

- [x] Focus on a single fix or feature; remove any unrelated formatting or code changes
- [ ] Add unit tests showing fix or feature works; all tests pass
- [ ] Mention any [related issues](https://github.com/premake/premake-core/issues) (put `closes #XXXX` in comment to auto-close issue when PR is merged)
- [x] Follow our [coding conventions](https://github.com/premake/premake-core/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] Minimize the number of commits
- [ ] Align [documentation](https://github.com/premake/premake-core/tree/master/website) to your changes

### CODE REVIEW

**Review by KyrietS — APPROVED** [review]
It's for visuals only, right? Let's keep the website separate as it is completely different project using different technologies.

**Comment by Jarod42** [comment]
> It's for visuals only, right? Let's keep the website separate as it is completely different project using different technologies.

Not only Visual studio, there are Codelite, XCode which handle None projects too.
And indeed it is not for build, but it allows editing from IDE.

**Comment by KyrietS** [comment]
@tritao Do you have the website built? I mean, do you have `node_modules` in the website/ folder? The website itself consists of ~400 files. I'm assuming the Visual Studio does something under the hood?

@Jarod42 can you confirm the issue?

**Comment by KyrietS** [comment]
We definitely want to exclude it then 😅

**Comment by Jarod42** [comment]
I don't have those generated files (I don't build them)

**Pull request merged**
