### PR TITLE
Update curl to 7.53.1

### PR DESCRIPTION
**Pull request by aleksijuvani**
Should fix an issue where all HTTPS requests on Windows versions older than Windows 8.1 or Windows Server 2012 R2 were failing with the error message "schannel: failed to retrieve ALPN result" (https://github.com/curl/curl/issues/840). Doesn't look like there are any breaking changes as far as I can tell.

### CODE REVIEW

**Comment by aleksijuvani** [comment]
Looks like Linux and macOS builds are failing. I'll take a look.

**Comment by aleksijuvani** [comment]
There we go.

**Comment by tritao** [comment]
lgtm

PS: We might want to consider submodule'ing curl in the future.

**Comment by tvandijck** [comment]
@tritao I wish we could, but we hand-crafted our curl_config.h to work for the platforms we currently sort of support.... curl itself when build through ./configure, or cmake generates that file through autoconf like tools... Basically we have 'local' changes to curl that have to be integrated into any updates.

**Pull request merged**
