### PR TITLE
Add UnsignedChar API

### PR DESCRIPTION
**Pull request by tdesveauxPKFX**

### CODE REVIEW

**Comment by samsinsane** [comment]
Could Clang, MSC, VS, XCode and CodeLite support this too?

**Comment by tdesveauxPKFX** [comment]
I thought clang used shared flags from gcc but while it does it's not as I though so yeah I will implement it.

I will have to look for the others.

**Comment by samsinsane** [comment]
@tdesveauxPKFX yeah it's a tricky one, *some* things aren't supported on Clang. Best example is `floatingpoint "Strict"`, but `floatingpoint "Fast"` is, which was super annoying when we didn't have a `Default` option for it.

**Comment by samsinsane** [comment]
Amazing stuff! Thanks for adding in support for all of the other actions and toolsets!

**Pull request merged**
