### PR TITLE
OSX and Linux SSL support and OSX fixes

### PR DESCRIPTION
**Pull request by mversluys**
Small changes to get premake-core compiling.
Support for SSL added using Darwin SSL.
Tested on OSX Yosemite with Xcode 7.1

### CODE REVIEW

**Comment by starkos** [comment]
These look okay to me—Tom, do these changes cause any issue at your end?

**Comment by tritao** [comment]
LGTM except the `CURL_CA_BUNDLE` change which should probably be limited to non-Linux platforms.

**Comment by tvandijck** [comment]
> Tom, do these changes cause any issue at your end?

These changes come from here at Blizzard actually, so I think we're good ;)
But @tritao has a good point...

**Comment by mversluys** [comment]
SSL wasn't enabled on Linux, so wasn't worried about the CURL_CA_BUNDLE.

Made the necessary changes to Linux so that it will use OpenSSL for SSL, if it's installed (it looks for the presence of the ssl library).

The CURL_CA_BUNDLE was changed to do the same test that's in the configure step for the curl library and looks in several locations for the certificates. The existing curl code was configured on CentOS 5 which uses a different location than other distros.

Tested on Ubuntu 15.10.

**Comment by tritao** [comment]
Awesome, LGTM.

**Comment by starkos** [comment]
Thanks everyone!

**Pull request merged**
