### PR TITLE
fix path.translate in gmake backend.

### PR DESCRIPTION
**Pull request by tvandijck**

### CODE REVIEW

**Comment by tvandijck** [comment]
hmm.. this one breaks a few tests... :( I'll revisit...

**Comment by samsinsane** [comment]
Does #307 cover this fix? It should provide the target OS separator instead of assuming the Windows separator.

**Comment by starkos** [comment]
It looks like #307 is complementary, yes. We'll probably have to specify an OS in the Gmake test suite setup functions to get consistent behavior then (perhaps already covered by #307).

**Comment by tritao** [comment]
For reference, the failing test is:

```
make_cs_response.listResponseRules: ...premake-core/tests/actions/make/cs/test_response.lua:65: (6) expected:
	$(SILENT) if exist $(RESPONSE) del $(OBJDIR)\MyProject.rsp
...but was:
	$(SILENT) if exist $(RESPONSE) del $(OBJDIR)/MyProject.rsp
stack traceback:
	...premake-core/tests/actions/make/cs/test_response.lua:65: in function <...premake-core/tests/actions/make/cs/test_response.lua:51>
running time : 1.13
1363 tests passed, 1 failed
```

Can we just disable this test for now and merge this? The C# backend has been broken on non-Windows platforms for at least two months now, this is affecting (breaks compilation) of all of our projects using Premake.

**Comment by tritao** [comment]
I've reworked this code, please check pull request #347.

**Pull request closed without merging**
