### PR TITLE
Fix `premake.findProjectScript` of previous commit.

### PR DESCRIPTION
**Pull request by Jarod42**
**What does this PR do?**

Fix https://github.com/premake/premake-core/pull/2066

**Did you check all the boxes?**

- [x] Focus on a single fix or feature; remove any unrelated formatting or code changes
- [ ] Add unit tests showing fix or feature works; all tests pass
- [ ] Mention any [related issues](https://github.com/premake/premake-core/issues) (put `closes #XXXX` in comment to auto-close issue when PR is merged)
- [x] Follow our [coding conventions](https://github.com/premake/premake-core/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] Minimize the number of commits
- [ ] Align [documentation](https://github.com/premake/premake-core/tree/master/website) to your changes

### CODE REVIEW

**Review by nickclark2016 — COMMENTED** [review]
Just a minor nit, can we give `f` a more descriptive name? Other than that, LGTM.

**Comment by Jarod42** [comment]
Any proposal?
`compiled_chunk`, `func`, `chunk_func`?

**Comment by nickclark2016** [comment]
Either the first or last is fine to me. Just something that gives me an idea of what's going on if I've gotta touch that code in the future.

**Comment by Jarod42** [comment]
Renamed to `compiled_chunk`.

**Review by nickclark2016 — APPROVED** [review]

**Comment by nickclark2016** [comment]
Just a sanity check, but this is verified, correct?

**Comment by Jarod42** [comment]
Verified locally and with: [premake-sample-projects/actions](https://github.com/Jarod42/premake-sample-projects/actions) (Test fix for premake master.)
(Whereas [premake5-ubuntu-gmake](https://github.com/Jarod42/premake-sample-projects/actions/runs/5821462791) show the issue).

**Pull request merged**
