### PR TITLE
path.translate fix

### LINKED ISSUE #86: path.translate always translates to \
if (lua_gettop(L) == 1) {
		sep = "\\";
	}

Shouldn't that be dependent on the OS that path.translate is called on?

### PR DESCRIPTION
**Pull request by samsinsane**
path.translate now uses the target OS separator by default instead of Windows separator. Fixes #86

The wiki will need to be updated to reflect this change when/if it's merged.

### CODE REVIEW

**Comment by samsinsane** [comment]
I wasn't expecting so many tests to fail, I'm going to go through and update the tests to use `path.translate` where possible, I should have this done by the end of tomorrow. @starkos does this sound ok, or is there a better way to do this?

**Comment by starkos** [comment]
Why are the tests failing?

**Comment by samsinsane** [comment]
The tests are expecting `\` in paths but are getting `/` because the tests are being run on Linux. I was thinking of setting `_OPTIONS["os"] = "windows"` but I feel like that would other unintended side effects.

**Comment by starkos** [comment]
Are they tests for Visual Studio? If so, you can also set `_ACTION = "vs2010"` (or an appropriate version) in setup.

**Comment by samsinsane** [comment]
They're not just for Visual Studio, I believe some of them already set that value and are still failing. Unless I'm mistaken, setting that shouldn't change the way paths are output?

**Comment by starkos** [comment]
> wouldn't it be easier to introduce a "os.separator" property, and do this string compare only once at startup?

You can't use the local system separator, because you might be generating for a different platform, i.e. generating a VS project from Linux.

> They're not just for Visual Studio...Unless I'm mistaken, setting that shouldn't change the way paths are output?

Setting the action to Visual Studio implicitly sets the OS to "windows" (and `_ACTION = "xcode4"` should set the OS to "macosx").

If you can point me to a specific test that you're having trouble with I can take a look and see if I have any better suggestions.

**Comment by tvandijck** [comment]
> You can't use the local system separator, because you might be generating for a different platform, i.e. generating a VS project from Linux.

correct, but I was suggesting to base it off of os.get() still... just once at startup.
instead of for every path.translate... I know you guys don't really care much about performance, but it's a big deal for us...

**Comment by samsinsane** [comment]
Oh ok, I'll have a look when I get a chance, maybe I misread the test setup. Thanks for the tip! I'll let you know how I go.

**Comment by starkos** [comment]
> correct, but I was suggesting to base it off of os.get() still... just once at startup.

Sorry, it looked like you were suggesting looking at `package.path`. Yes, I agree, keeping this function quick is important, it gets called a *lot*. You will have to be sure the action's `os` value has been picked up—I think this happens in `action.set()` but I'm not sure where in the bootstrapping that is called, and whether that is before or after the first call to `path.translate()`.

**Comment by samsinsane** [comment]
I'll look into moving the check so it isn't run all the time, it definitely isn't in the most ideal location.

**Comment by samsinsane** [comment]
@starkos it looks like setting `_ACTION` directly doesn't change the OS, but using `premake.action.set()` does, should I use this instead?

**Comment by starkos** [comment]
I think `action.set()` makes more sense than `_OPTION["os"] = "windows"` for sure.

**Comment by samsinsane** [comment]
Alright, I'll go through and update the tests to use `action.set()` instead of `_ACTION`.

**Comment by samsinsane** [comment]
@starkos I've got all the premake-core tests passing, just left with ones in codelite, d and monodevelop modules. The `action.set()` function sets `_OS`, should I just set that to `windows` for those test suites?

**Comment by starkos** [comment]
I would check with Manu on how to handle those.

**Comment by TurkeyMan** [comment]
Yeah, just spoke with Sam; the question is, do we use `path.translate` on the expected result in unit tests, or do we set the OS explicitly and continue expecting a literal?
We were both leaning towards `path.translate`-ing the expected unit test output... @starkos what do you reckon?

**Comment by tvandijck** [comment]
I think as long as path.translate itself is properly tested independently, using path.translate in other tests should not be a problem...

**Comment by starkos** [comment]
What tests are we talking about here?

**Comment by samsinsane** [comment]
The four tests are:
- `codelite_workspace.onNestedProjectPath` in `test_codelite_workspace.lua`
- `codelite_workspace.onExternalProjectPath` in `test_codelite_workspace.lua`
- `mono_d.OnProject_objectsDirectory` in `test_monodevelop.lua`
- `monodevelop_project_config.OnProject_OutputPath` in `test_config.lua`

**Comment by starkos** [comment]
Thanks! Is there any reason for CodeLite or MonoDevelop to be using Windows-style separators? Since they are cross-platform tools it seems like the more generic forward slash would be better here?

If that's not correct and they are supposed to be using backslashes, is that for all platforms or just Windows? And is that for projects that are generated on Windows, or when a configuration's `system` is set to `"Windows"`?

**Comment by tritao** [comment]
I asked my co-worker (works on MonoDevelop) and he told it's due to compatibility with MSBuild.

**Comment by samsinsane** [comment]
I've got PRs open on the premake-codelite, premake-dlang and premake-monodevelop modules, once they're merged in, I'll update this PR and that should fix up all the tests.

**Comment by TurkeyMan** [comment]
And they're merged! Thanks guys!
Sorry again for basically disappearing recently! >_<

**Comment by samsinsane** [comment]
Thanks @TurkeyMan! Looks like there was another update to the codelite project that added another test, I'll need to fix that one up too.

**Comment by samsinsane** [comment]
Ok, the update didn't add another test it actually broke the test. Can someone with codelite experience/knowledge take a look at this broken test? The `WorkingDirectory` attribute in the `General` tag is expecting `bin/Debug` by default and we're emitting an empty string, is this valid?

**Comment by tritao** [comment]
Any news about this pull? It would be great if this fix could be merged soon.

**Comment by samsinsane** [comment]
I just need a codelite user to give me a bit of info on what to do with the codelite module. I've been pretty busy lately and haven't had much time to follow up on this issue.

**Comment by TurkeyMan** [comment]
Me too! Sorry again. My overtime counter is off the charts.

Just looking at this; not quite sure what the workingdir should be... currently it is:
```
local targetpath = project.getrelative(prj, cfg.buildtarget.directory)
local workingdir = iif(isExe, targetpath, "")
```

That doesn't seem right... and apparently this change causes that logic to change somehow? Seems weird.
We have the `debugdir` api, do we reckon that should be used to set `WorkingDir` in this context? Otherwise I think I leave it blank, and let the user set it manually if they want to.
I've never been quite clear on what `debugdir` is meant to mean. Anyone know the difinitive word on that?

**Comment by tritao** [comment]
`debugdir` is supposed to set the working directory used when launching the debugger.

**Comment by TurkeyMan** [comment]
Right, 'used when launching the debugger', but not 'in general', and that's what makes it awkward... we don't have a specification for working dir when not debugging.

**Comment by tritao** [comment]
I'm not sure what you mean about "specification for working dir when not debugging", what do you have in mind?

**Comment by TurkeyMan** [comment]
I mean, 'working dir' is a concept that exists both while debugging and not... but we only control one of the cases. The line in question here is the not-while-debugging case.
So I'm thinking resolution here would be to emit a blank entry?

**Comment by tritao** [comment]
OK now I understand what you mean. I think I originally introduced the `debugdir` and called it that way because that's the terminology used by VS. If other IDEs support setting the working directory for non-debugging scenarios we could generalize the naming of this API.

**Comment by TurkeyMan** [comment]
Even visual studio has both concepts (i think?).
So, votes for renaming `debugdir` to `workingdir`, or adding a second api such that both cases are specified independantly?
Perhaps a solution where `workingdir` is applied to both cases by default, and `debugdir` may override `workingdir` in the debug case if specified...?

**Comment by starkos** [comment]
> So, votes for renaming `debugdir` to `workingdir`

**Comment by samsinsane** [comment]
@starkos was this supposed to get closed?

**Comment by starkos** [comment]
No, no idea what happened there. Reopening!

**Comment by samsinsane** [comment]
@starkos thanks for sorting out the issues with the codelite module in core. I think that was the only thing holding this PR up, should be good to merge now. Let me know if there's any issues that I need to fix up.

**Comment by samsinsane** [comment]
Has anyone had a chance to go over this PR? It'd be nice to finally have this sorted out, and merged into core.

**Comment by tvandijck** [comment]
This might be nitpicking, but even though the "premake.action.set" change is in a separate commit, could we do that in a separate PR... I find that a really good change that I would like to see irrespective of the path.translate fix..

**Comment by starkos** [comment]
I'm a little nervous about this one as that function is used all over the place, but okay, let's see how it goes!

**Pull request merged**
