### PR TITLE
These are a bunch of fixes and changes we made here at Blizzard. 

### PR DESCRIPTION
**Pull request by tvandijck**
Same as on BitBucket, with the os.delete, and the parse for known options removed..
the parse for known options I'll put in a separate request to discuss further..

### CODE REVIEW

**Comment by TurkeyMan** [comment]
This is awesome. Thanks heaps guys!
I wonder if we should split these into many PR's for individual consideration?
I can't see a lot in here that's controversial though.

**Comment by tvandijck** [comment]
that editorconfig plugin is the shizzle ;) thank you very much for sharing that little gold gem...

**Comment by TurkeyMan** [comment]
Yeah, really. Couldn't live without it! Especially at work ;)

**Comment by TurkeyMan** [comment]
Yeah, really. Couldn't live without it! Especially at work ;)

**Comment by tvandijck** [comment]
Fixed the tab, and I found a bug in the oven.bubbleFields yesterday which affects usage of tokens in "vpaths", which we enabled.

**Comment by tvandijck** [comment]
Closing this... I split most of these out into individual pull requests.

**Pull request closed without merging**
