### PR TITLE
Reworked filename pattern matching to allow for more complex patterns.

### PR DESCRIPTION
**Pull request by tvandijck**

### CODE REVIEW

**Comment by TurkeyMan** [comment]
This is a pretty aggressive change, kinda hard to review.
I'd really like to see this patch bundled with a decent collection of unit tests demonstrating what it designed to allow.
These sorts of changes always make me the most uncomfortable. I don't usually like to weigh in on them ;)

In theory, it sounds awesome to me (from the description you gave elsewhere), but it's really hard to predict the effects it may have on existing projects.
I'd say the benefits (as advertised in your email) are clear, and I'd be inclined to accept it.

**Comment by TurkeyMan** [comment]
I wonder if @Bekenn who appears to have authored the commit can comment?

**Comment by Bekenn** [comment]
Sure, I can answer any questions you have.  I'm afraid the only "tests" I wrote were the scripts for SC2, which make use of this feature in order to support locale-specific resources in an Xcode-friendly manner.  The problem I wanted to solve was that file path pattern matching only matched a single wildcard in the search string, which made more complex paths impossible.  I wanted to make this possible:

xcode_resources {
    '*.lproj/**/*.txt' -- all locale-specific .txt files
}

This feature is in use and works well in all of our projects that generate app bundles, and doesn't appear to have broken anything else.

**Comment by TurkeyMan** [comment]
Okay, so would you say the main event in the patch is to support multiple occurrences of wildcards?

**Comment by Bekenn** [comment]
That's correct.

**Comment by TurkeyMan** [comment]
Okay, thanks. There is also PR #182, #183, that I think you(?) wrote which Tom said he couldn't give much info about. If you wouldn't mind giving some quick summaries?

**Comment by tvandijck** [comment]
I rebased it on top of the other PR that just got merged... so all should merge now.

**Comment by TurkeyMan** [comment]
I'm inclined to click the merge button, but I think @starkos should be the one to click it in this case :)

**Comment by starkos** [comment]
I'd like to have a chance to take a quick test run with if first if that's okay. I can add a few tests to `tests/base/test_os.lua` while I'm at it.

**Comment by starkos** [comment]
Sorry, I was swamped this weekend and didn't get a chance to review. Still trying to get to it.

**Comment by starkos** [comment]
Rebased, added test, merged manually. Thanks for this!

**Pull request closed without merging**
