### PR TITLE
Add conditional behavior to global variables, add systemversion as first implementation

### PR DESCRIPTION
**Pull request by redorav**
The UI can't do this but setting it manually actually works. Fixes https://github.com/premake/premake-core/issues/936

### CODE REVIEW

**Comment by redorav** [comment]
Sure, I'm all for having a discussion about it. To me it doesn't sound so much "unsupported" as "not exposed" in the sense that there seem to be many things the .vcxproj can do that aren't in the UI. I totally see your point that there's a kind of risk in exposing these kinds of things, but my feeling is it looks more like a limitation of the UI than a limitation of the xml system they have in place. Perhaps it would be worthwhile to see what cmake does or try to find some better documentation coming from MS.

Regarding the changes, I'll make it more flexible so it can go in Globals or Config depending on settings.

**Comment by redorav** [comment]
Thanks for the feedback @starkos and @samsinsane , I'm currently investigating how to expand the Globals section to include conditionals as needed. The interesting thing about these modifications is that they are actually tweakable via the UI provided the condition was present there to begin with, so it's not like we're taking anything away from the user.

**Comment by redorav** [comment]
I've moved systemversion back to Globals, and also create conditional global entries in the vcxproj. One thing I've not found a straightforward way of doing is to not create the property groups if no entries are going to be populated. I think the assumption is that there's always something that's going to populate it. Any suggestions? I've added an example test, but I mean to expand it once we agree on a final implementation.

**Comment by starkos** [comment]
> One thing I've not found a straightforward way of doing is to not create the property groups if no entries are going to be populated

If you search the source for "io.capture" you can find some places where we do that. You run the code and capture the output, and then check to see if the output is empty before writing it out. Let me know you need help with it and I'll throw together a proper example.

**Comment by redorav** [comment]
I think I managed to do it via premake.capture() which I guess was renamed at some point from io.capture.

**Comment by redorav** [comment]
As soon as you're happy with the changes I've also fixed #1038 locally which relies on this PR to work, since this one allows setting conditions on globals and the other fix extends the function via premake.override.

**Comment by starkos** [comment]
@samsinsane, are you okay with this one? If so, feel free to merge.

**Pull request merged**
