### PR TITLE
Added new module that outputs the raw hierarchical structure of a solution

### PR DESCRIPTION
**Pull request by tvandijck**
This is extremely handy for debugging...

### CODE REVIEW

**Comment by benvanik** [comment]
Super useful, thanks for doing this! (I was thinking of doing it myself tonight :)

**Comment by starkos** [comment]
I'm currently working on a tutorial for authoring new actions which will show how I think "best practices" (shiver) should be done and a few improvements. Once that's done (should be soon) I'll loop back to this.

**Comment by starkos** [comment]
As I mentioned, I'm working on a similar but more comprehensive module to demonstrate how to create new actions. I had been exporting to JSON, though it just occurred to me now that if I exported to Lua tables instead you could then use Premake itself to manipulate the result.

If something like that were available, would this module still be useful? I think I'd rather decline this one for now?

**Comment by tvandijck** [comment]
We used it for debugging, but yeah, any other thing that would become available that we can use to that extend would work for us.... we just figured it might help someone...

**Comment by tvandijck** [comment]
Closing this, if we want this in the future, I'll reopen...

**Pull request closed without merging**
