### PR TITLE
Add build script integration.

### PR DESCRIPTION
**Pull request by tvandijck**
This adds the script that created the project to the project tree... pretty useful.

### CODE REVIEW

**Comment by starkos** [comment]
I'm not a fan of this one, I really don't want Premake sticking things into my project files outside of what I specify in my script. But open to additional opinions here.

**Comment by tvandijck** [comment]
I love it, because it allows me to edit the lua scripts from within my project... but I get what you are saying... maybe we can make it optional...

It's what nant and cmake do as well btw, I'm not sure if it is optional for those though..

**Comment by starkos** [comment]
Can you just add…

```lua
files { "**/premake5.lua" }
```

…to your project script (or something like it)? I get what your saying, and for my personal projects I often do this too. But most (all, I think actually) of the projects I set up in other environments do not include those scripts in the generated projects.

**Comment by TurkeyMan** [comment]
I've never had a problem with adding the scripts to my project explicitly. Is there a reason to do it automatically?

**Comment by tvandijck** [comment]
> Is there a reason to do it automatically?

Yeah, I'm lazy.

**Comment by TurkeyMan** [comment]
> Yeah, I'm lazy.

Surprising. I don't see much evidence for this ;)

**Comment by starkos** [comment]
> Yeah, I'm lazy.

Me either, I can hardly keep up (or not). Despite that, this one still makes me uncomfortable, hope you don't mind (too much).

**Comment by tvandijck** [comment]
;) no worries, we'll keep it as a local change..

**Pull request closed without merging**
