### PR TITLE
Fix context.mergeFilters

### PR DESCRIPTION
**Pull request by tdesveaux**
Fix related to #884.

This lead to a 10-15% performance drop for me.

### CODE REVIEW

**Comment by tvandijck** [comment]
As much as I agree that this fixes #884, the performance implications are a little too severe... we should really look at ways to do this more conditionally, so the impact is minimized.. So I'm going to mark this as "request changes"...

**Comment by tdesveauxPKFX** [comment]
@tvandijck I agree with this.
However, if someone can test on another project that would be good.
I tested this in our projects at work that were setup with a highly customized premake4 build and that I "adapted" to work in premake5.

I will still take a look to see what I can do to improve this.

**Comment by tdesveauxPKFX** [comment]
With this, the performance are no longer an issue, difference with previous implementation are marginal.
However, this works only for tags and not other terms that are tables.
As far as I know, this is not an issue for now but it might become one in the future.

Would implementing mergeFilters in c improve performances?

**Comment by tvandijck** [comment]
I don't know if it would be effective to do it in C... considering you then have to enumerate the table in C, you just end up with a whole lot of calls into lua api's anyway... I think the conditional approach is acceptable, and can always be extended.. I think it's really only the tags that suffer.

**Comment by tdesveauxPKFX** [comment]
I forgot to mention, I also removed the call to table.joinunique as we don't care about duplicate and it takes more time to check duplicates than just copy the whole thing.

I did not remove the table.joinunique function though, I should remove it before merging this.

**Pull request merged**
