### PR TITLE
add 'entrypoint' API.

### PR DESCRIPTION
**Pull request by tvandijck**

### CODE REVIEW

**Comment by TurkeyMan** [comment]
LGTM. We should probably leave an open issue to remind supporting the other compilers, but this fixes the existing problem case.

**Comment by TurkeyMan** [comment]
Can rebase this? I'd like to see it merged.

**Comment by tvandijck** [comment]
done, I also fixed up a whole bunch of incorrect whitespace... I don't know what happened to that file, but it definitely made this merge a lot more complex than needed.

**Comment by TurkeyMan** [comment]
Are you aware of `.editorconfig` files? (http://editorconfig.org/)
There's one in premake root. Assuming you're a VS user, there is an EditorConfig plugin which can be installed by the in-game extension manager (Tools -> Extension Manager); search for EditorConfig.
Most editors have a parallel solution.
You shall never have whitespace problems again! :P

**Comment by starkos** [comment]
I have the Sublime Text plugin installed…though maybe it isn't on all of my development VMs? I'll check and make sure.

**Comment by tvandijck** [comment]
Yeah, I got it installed for both sublime and visual studio too...
but it doesn't really help in all cases unfortunately... for example it doesn't automatically fix scoping of "end" etc...

**Pull request merged**
