### PR TITLE
macOS os.getversion() improvements

### PR DESCRIPTION
**Pull request by noresources**
**What does this PR do?**
* Read macOS system version from system property list instead of reading kernel version.
* Add description for latest versions

**How does this PR change Premake's behavior?**
* Same behavior for previously supported OS versions
* Correct version number for any new version of macOS instead of 0.0
* Maybe a bit slower

**Anything else we should know?**
* I have kept the previous method as a fallback if the property list is removed in future releases.
* The big switch over kernel version has been replaced by `info->minorversion = kern_major - 4;`. The relation is correct for all previously supported versions and probably for future ones.
* The description will remain "Mac OS X" for new versions until a manual update of the code.

There is simpler methods to retrieve the OS version but they use [private API](https://opensource.apple.com/source/DarwinTools/DarwinTools-1/sw_vers.c.auto.html) or Objective-C code.

Add any other context about your changes here.

**Did you check all the boxes?**

- [x] Focus on a single fix or feature; remove any unrelated formatting or code changes
- [ ] Add unit tests showing fix or feature works; all tests pass
- [ ] Mention any [related issues](https://github.com/premake/premake-core/issues) (put `closes #XXXX` in comment to auto-close issue when PR is merged)
- [ ] Follow our [coding conventions](https://github.com/premake/premake-core/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] Minimize the number of commits

### CODE REVIEW

**Comment by samsinsane** [comment]
> There is simpler methods to retrieve the OS version but they use private API or Objective-C code.

Is there a simpler Objective-C version that uses public APIs? How much simpler?

@starkos would you object to having a simpler implementation written in a different language? The code is already platform specific, being written in the "platform language" isn't going to make that much of a difference.

**Comment by noresources** [comment]
@samsinsane Objective-C code relies one Cocoa AppKit framework. It is not simpler, just use standard APIs.
[Here is an implementation example](https://github.com/openjdk/jdk/blob/master/src/java.base/macosx/native/libjava/java_props_macosx.c#L237)

**Comment by starkos** [comment]
I would not object to using Objective C in the macOS build.

**Comment by noresources** [comment]
I have made some exeperiments with the Objective-C API and the sw_vers command line tool
1. If I modify the SystemVersion.plist values, both sw_vers and the Objective-C API returns the modified values immediatly. So, the current pull request does exactly what Apple is doing under the hood
2. The Objective-C API is only available on OSX 10.10+ (with a deprecated alternative)
3. To compile Objective-C, Bottstrap.mak and premake4/5.lua have to be changed.

**Comment by starkos** [comment]
Thanks for doing that research. @samsinsane I'm okay with the current, simpler plist approach, if you have no objections?

**Pull request merged**
