### PR TITLE
Port user guide pages from wiki

### PR DESCRIPTION
**Pull request by starkos**
**What does this PR do?**

Port all of the user guide content from the wiki to the new website.

**How does this PR change Premake's behavior?**

Website only, no code changes.

**Anything else we should know?**

There is still more to do before taking the site live; see #1547.

**Did you check all the boxes?**

- [x] Focus on a single fix or feature; remove any unrelated formatting or code changes
- [ ] ~Add unit tests showing fix or feature works; all tests pass~
- [x] Mention any [related issues](https://github.com/premake/premake-core/issues) (put `closes #XXXX` in comment to auto-close issue when PR is merged)
- [x] Follow our [coding conventions](https://github.com/premake/premake-core/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] Minimize the number of commits

*You can now [support Premake on our OpenCollective](https://opencollective.com/premake). Your contributions help us spend more time responding to requests like these!*

### CODE REVIEW

**Comment by KyrietS** [comment]
All looks great. Just one little thing. I'd like you to understand the difference between *raw links* and *links to other pages* in Docusaurus. (or maybe you already know)

**raw links**:

```
[text](https://www.wikipedia.org/)
[text](some/path.html)
[text](/assets/premake.zip)
[text](how-to-help)
```

**links to other pages**:

```
[text](some/path.md)
[text](How-To-Help.md)
[text](how-to-help.md)  # Wrong. Broken link. Filename is case sensitive.
```

The difference is that *raw links* are not checked to see if the resource exists. Links to particular Markdown pages on the other hand *are* checked. So if you remove or rename a Markdown file, you will get a warrning / error when building the website (CI will fail). So we can be sure that no broken links exist in our docs.

Also, I saw you changed some links to lowercase variants, e.g. `[text](Building-Premake.md)` was changed to `[text](building-premake)`. Unfortunately link to `Building-Premake.md` will always be resolved as `/docs/Building-Premake` no matter what the value of the parameter `slug:` is. So we have no control over urls (except naming files correctly ofc).

Additional advantage of *\*.md links* over *raw links* is that they work when you browse Markdown docs on GitHub. 

I don't want to say that using *raw links* is incorrect. Many projects use them. But I think that broken links validation functionality is good thing to have as well.

Regardless of what decision you make about the links, I think it's great and can be merged.

**Comment by KyrietS** [comment]
**EDIT:** In my previous comment I said that using `[text](name-of-file)` instead of `[text](Link-To-File.md)` won't give us warnings about broken links. But it's not true: https://v2.docusaurus.io/docs/docusaurus.config.js/#onbrokenlinks

All looks great. Just one little thing. We still have many broken links warnings.

For example: 

* `Home.md` link to `What's-New-in-5.0.md` is broken.
* in `Command-Line-Arguments.md` there is `Adding-a-new-Action` instead of `Adding-New-Action`.
* many broken links in `Lua-Library-Additions`. Most of them are to the files I deleted as they were auto-generated without sensible content.

run `npm run build` to see all warnings.

For CI job I'd like to change `onBrokenLinks: 'warn'` to `onBrokenLinks: 'throw'` so every version of our website is going to have no broken links.

**Comment by starkos** [comment]
I guess I misunderstood how/when broken links were reported. I've now run `npm run build` and fix all issues, and I also added a note to `README.md` for future developers. If I don't hear otherwise I'll go ahead and merge this later today.

> For CI job I'd like to change onBrokenLinks: 'warn' to onBrokenLinks: 'throw'

Yes, definitely.

**Comment by KyrietS** [comment]
Warnings about broken markdown links (e.g. `[text](Some-File.md)`) are reported in dev mode when you run `npm start`. But raw links, like `[text](some/relative/path)` are checked during build process only.

Now it looks good to me 👍

**Comment by starkos** [comment]
Thanks for the review. Merging now, and then I'll get started on the index and download landing pages.

**Pull request merged**
