### PR TITLE
Use vswhere.exe in Windows pipeline

### LINKED ISSUE #1819: Windows pipeline upgrade to `windows-2022`
Windows pipeline is failing. These lines seem to be a problem:

```yaml
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
        nmake -f Bootstrap.mak MSDEV=vs2019 windows-msbuild PLATFORM=${{ matrix.platform }} CONFIG=${{ matrix.config }}
```

Recently, GitHub updated the software on their Windows virtual machines and Visual Studio cannot be found under the given path.

Currently, Visual Studio path is:

```
C:\Program Files\Microsoft Visual Studio\2022\Enterprise
```
According to [Windows2022-Readme](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md#visual-studio-enterprise-2022)

## Solution

Instead of hardcoding the path to the `vcvarsall.bat` script again, I suggest using the `vswhere.exe` program, which is [available globally](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md#tools) on the machine running the pipeline.

For example, the following running of the `vswhere.exe` program:

```
vswhere.exe -find VC\Auxiliary\Build\vcvarsall.bat
```

should print the following result:

```
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat
```

Which is exactly what we are looking for. But...
Unfortunately, I don't know how to run a bat script whose path is printed by another command. It would be easier in PowerShell, but our stage uses legacy cmd.exe. Maybe it's time for a change?

### PR DESCRIPTION
**Pull request by KyrietS**
**What does this PR do?**

Use `vswhere.exe` to get a path to the `vcvarsall.bat`.
My approach is that I use PowerShell to execute `vswhere.exe` and save its result to variable (`$vcvarsall_path`).
Then, run the script in legacy `cmd.exe`.

Resolves #1819 

**Did you check all the boxes?**

- [x] Focus on a single fix or feature; remove any unrelated formatting or code changes
- [x] Add unit tests showing fix or feature works; all tests pass
- [x] Mention any [related issues](https://github.com/premake/premake-core/issues) (put `closes #XXXX` in comment to auto-close issue when PR is merged)
- [x] Follow our [coding conventions](https://github.com/premake/premake-core/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] Minimize the number of commits
- [x] Align [documentation](https://github.com/premake/premake-core/tree/master/website) to your changes

*You can now [support Premake on our OpenCollective](https://opencollective.com/premake). Your contributions help us spend more time responding to requests like these!*

### CODE REVIEW

**Review by nickclark2016 — APPROVED** [review]
Sorry it took so long for me to review. Can you rebase to latest master and I'll pull it in?

**Comment by KyrietS** [comment]
Rebased on top of master.
Please, don't feel pressured to work fast. We are here because of passion, not duty. Thanks! 😊

**Comment by nickclark2016** [comment]
I'm blanking. What merge strategy do we use again? I'm happy with changes

**Comment by KyrietS** [comment]
Do we have a _strategy_? 😅
I always click the "Merge pull request" button. I know that it creates a redundant merge commit but it has never been a problem. Starkos has always done it this way, so I do doing the same 😁

**Comment by nickclark2016** [comment]
> Do we have a _strategy_? 😅 I always click the "Merge pull request" button. I know that it creates a redundant merge commit but it has never been a problem. Starkos has always done it this way, so I do doing the same 😁
> 
> EDIT: But if you're asking about who should click the "Merge" button on GitHub then I'm not aware of any rules. Maybe we should have some 😄. I personally try not to merge my own commits but when it's kind-of urgent then I wouldn't hesitate.

Ahh, talking about merge strategy. Create a Merge Request, Squash and Merge, Rebase and Merge

**Comment by KyrietS** [comment]
> Ahh, talking about merge strategy. Create a Merge Request, Squash and Merge, Rebase and Merge

See Premake's commit history. In most cases, we use Merge Request. As far as I know, no strategy has been agreed upon

**Pull request merged**
