### PR TITLE
Fix gmake dependencies

### LINKED ISSUE #981: Makefile target dependencies aren't correct
I've noticed that the make output has lots of errors with rule dependencies, and this leads to problems with multi-core builds (ie, `make -j2` or more)

Consider:
```make
all: prebuild prelink $(TARGET) | $(TARGETDIR) $(OBJDIR)
	@:
```
What this says is that `all` depends on `prebuild` `prelink` and `$(TARGET)`, but it misses the hierarchy of dependency.
Truth is, `all` depends on `$(TARGET)`, which depends on `prelink`, which depends on `$(OBJECTS)`, which may-or-may-not depend on `$(PCH)`, which depends on `prebuild`.
We need to restructure the dependency resolution into the proper dependency structure, otherwise multi-threaded doesn't work.

Currently, `-j3` may cause `prebuild`, `prelink`, and `$(TARGET)` to all be built at the same time in parallel, which is wrong, since each step may depend on successful completion of the prior steps.

### PR DESCRIPTION
**Pull request by TurkeyMan**
Attempt to fix #981 

Note, this patch doesn't implement any logic to prevent execution of the prebuild step if the project is not dirty... it will ALWAYS run prebuild, just like gmake output always has, but the deps should now be structured that parallel builds work.

### CODE REVIEW

**Comment by tvandijck** [comment]
Make sure you discuss this change with @bwhittle (at World of Warcraft).
He did most of the PCH related fixes earlier last year.

Other then the test failures, the change looks fine to me.

**Comment by TurkeyMan** [comment]
This has been tested now on a large project.

**Comment by TurkeyMan** [comment]
If someone wants to bless, this makes parallel builds work with make.

**Comment by TurkeyMan** [comment]
Sure, I can approve til the cows come home (I created this github account!) :P
But I totally wanted someone else to give this one a good once-over, since it feels pretty dangerous to me.

**Pull request merged**
