### PR TITLE
Visual Studio added explicit C++17 option

### PR DESCRIPTION
**Pull request by Enhex**
More correct than staying with `latest`.

### CODE REVIEW

**Comment by catb0t** [comment]
You'll need to update the tests or add more tests. Travis and AppVeyor fail because 

```xml
Running action 'test'...
vstudio_vs2010_compile_settings.onLanguage_Cpp17_VS2017: ...e/modules/vstudio/tests/vc2010/test_compile_settings.lua:1193: (5) expected:
	<LanguageStandard>stdcpplatest</LanguageStandard>
...but was:
	<LanguageStandard>stdcpp17</LanguageStandard>
fulltext:
<ClCompile>
	<PrecompiledHeader>NotUsing</PrecompiledHeader>
	<WarningLevel>Level3</WarningLevel>
	<Optimization>Disabled</Optimization>
	<LanguageStandard>stdcpp17</LanguageStandard>
</ClCompile>
stack traceback:
	...e/modules/vstudio/tests/vc2010/test_compile_settings.lua:1193: in function <...e/modules/vstudio/tests/vc2010/test_compile_settings.lua:1188>
vstudio_vs2010_compile_settings.onLanguage_Cpp17_VS2015: ...e/modules/vstudio/tests/vc2010/test_compile_settings.lua:1178: (5) expected:
	<AdditionalOptions>/std:c++latest %(AdditionalOptions)</AdditionalOptions>
...but was:
	<AdditionalOptions>/std:c++17 %(AdditionalOptions)</AdditionalOptions>
fulltext:
<ClCompile>
	<PrecompiledHeader>NotUsing</PrecompiledHeader>
	<WarningLevel>Level3</WarningLevel>
	<Optimization>Disabled</Optimization>
	<AdditionalOptions>/std:c++17 %(AdditionalOptions)</AdditionalOptions>
</ClCompile>
stack traceback:
	...e/modules/vstudio/tests/vc2010/test_compile_settings.lua:1178: in function <...e/modules/vstudio/tests/vc2010/test_compile_settings.lua:1173>
1694 tests passed, 2 failed in 5.06 seconds
```

**Comment by catb0t** [comment]
I think you have to change it one more place since the builds are still failing. I recommend you run the tests on your own machine too!

**Comment by pdoane** [comment]
We still need a way to be able to generate stdcpplatest for VS2017 versions before stdcpp17 is recognized.  It's fine to call that C++latest though.

**Comment by Enhex** [comment]
The error is for VS2015 and I don't have it installed currently. I'll find time for that later on.

@pdoane C++latest isn't good enough for all cases. For example if you want to explicitly restrict your project to C++17 for compatibility reasons, making sure nothing that's not supported by C++17 but does by C++latest doesn't make it in.

For older VS minor versions Premake will have to provide a way to select them. Right now you can only select the major releases.
In the meanwhile if you stick with an old version of VS, you can also stick with an old version of Premake that matches it.

**Comment by pdoane** [comment]
> C++latest isn't good enough for all cases.

I didn't say that it was.  I'm in support of having "C++17" map to /std:c++-17.  I said we still need a way to generate /std:c++-latest.  That is the only way to enable post C++17 functionality with the recent versions and the only way to enable C++17 draft functionality in the older versions.

Adding another option as I suggested makes the mapping very sensible:

  cppdialect "C++latest" -> /std:c++-latest
  cppdialect "C++17" -> /std:c++-17

It's kind of similar to the "C++0x" variations for gcc/clang.

> In the meanwhile if you stick with an old version of VS, you can also stick with an old version of Premake that matches it.

That isn't a viable option for us.

**Comment by Enhex** [comment]
@pdoane adding "C++latest" cppdialect is a much cleaner solution, I'm in favor of it.

**Comment by tvandijck** [comment]
Do we close this?

**Comment by starkos** [comment]
This looks like it is good to close. Feel free to reopen with changes as appropriate.

**Pull request closed without merging**
