### PR TITLE
Add Algolia search

### PR DESCRIPTION
**Pull request by KyrietS**
Sorry that it's taken me so long to make this little change 😅 

**What does this PR do?**

Added great instant search-box. Search is demonstrated on my [demo website](https://kyriets.github.io/premake-core/). The only change I need to do in order for this search to actually show our docs (currently search results are from Algolia Search) is to replace `apiKey` and `indexName`.

**How does this PR change Premake's behavior?**

*only website is affected*

**Anything else we should know?**

* Search index is updated once a day.
* We need to apply for API key to DocSearch. Only @starkos can do it. See Instructions below.

**Did you check all the boxes?**

- [x] Focus on a single fix or feature; remove any unrelated formatting or code changes
- [x] Add unit tests showing fix or feature works; all tests pass
- [x] Mention any [related issues](https://github.com/premake/premake-core/issues) (put `closes #XXXX` in comment to auto-close issue when PR is merged)
- [x] Follow our [coding conventions](https://github.com/premake/premake-core/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] Minimize the number of commits

Refers to #1547 

*You can now [support Premake on our OpenCollective](https://opencollective.com/premake). Your contributions help us spend more time responding to requests like these!*

**Applying for apiKey**

Algolia is free for open source projects that need search functionality for their *documentation websites*. It means that Premake is fully legitimate for using Algolia Search for free.

**Preconditions**:

* Only owner of the website/project can apply for DocSearch. (@starkos) ✔️
* Your website must be **publicly available**. ✔️
* Your website must be a **documentation website**. ✔️
* Your website must **have some final content** (no lorem ipsum allowed). ✔️

Additionaly they say:

> Your request will get priority:
> * If your project is open source. ✔
> * If you're using official integration. ✔️

So it's time to apply! I kindly ask you @starkos to do this here: https://docsearch.algolia.com/apply/  🙃 

After they validate your request, you'll get a public `apiKey` and `indexName`. You can then send it here. It's public anyway 👍

### CODE REVIEW

**Comment by starkos** [comment]
Request made. Would it make sense to put the API key in [GitHub secrets](https://docs.github.com/en/actions/reference/encrypted-secrets)? I guess it still might be accessible via a View Source… in the browser but at least it won't be hanging out in the sources?

**Comment by KyrietS** [comment]
> Would it make sense to put the API key in GitHub secrets?

GitHub secrets can be accessed only in workflow (yaml) files.

**Comment by starkos** [comment]
Response received:

```json
apiKey: '7440a29a5d611582272899683f54f54e', 
indexName: 'premake', 
```

Could you also add a quick blurb to the website README that mentions Algolia?

**Comment by KyrietS** [comment]
Works like a charm 😀

**Review by starkos — APPROVED** [review]
Thanks!

**Pull request merged**
