### PR TITLE
Added targetplatformversion API

### LINKED ISSUE #315: Visual Studio - Target Platform Version
Hi,
Is there a way of setting the VS2015/Project Properties/General/Target Platform Version? Its always set to 8.1 on Windows 10

Many Thanks.

### PR DESCRIPTION
**Pull request by samsinsane**
Fixes #315

### CODE REVIEW

**Comment by tritao** [comment]
lgtm

**Comment by starkos** [comment]
We currently use `system()` to choose the target OS, i.e. `system("Windows")`. Would it make sense to change this API to `systemversion()`?

OS X has a similar-ish concept where you can target min and max version ranges of core SDKs—Premake itself uses them via `linkoptions()` currently. It would be nice to unify the ideas if possible.

**Comment by samsinsane** [comment]
`systemversion` makes sense, I'll try to push the change when I get a chance.

Unifying the ideas sounds great, but I don't really know how this would work. `systemversion("min:max")`? Could that be confusing when the action or system doesn't support ranges?

**Comment by samsinsane** [comment]
@starkos updated to be `systemversion` and allows `systemversion("min:max")` for the OSX version system.

**Comment by tvandijck** [comment]
LGTM

**Comment by starkos** [comment]
Looks great, thanks! Can you throw together a doc page for the wiki to capture the "min:max" parameter format?

**Comment by samsinsane** [comment]
[Done!](https://github.com/premake/premake-core/wiki/systemversion) Let me know if I need to add more information.

**Comment by redorav** [comment]
I have a problem with this API. I've tried to use it as per the docs, but I'm getting a warning and the property doesn't get enabled. I have a simplest case that goes wrong.

```
workspace "Workspace"
	configurations { "Debug", "Release" }
	platforms { "A", "B" }
	location ("Workspace")
	
	systemversion("8.1")
	
	filter { "platforms:A" }
		system("windows")
		
	filter { "platforms:B" }
		system("windows")
		systemversion("10.0.15063.0")

project ("Project1")
	kind("WindowedApp")
	language("C++")
```

If I try to put that through premake alpha12, it complains that 

`** Warning: 'systemversion' on config 'Debug|B' differs from project 'Project1'; may be set out of scope`

Perhaps I'm doing something wrong? My expectation is that the filter in configuration B would apply to both Debug and Release but somehow it gets confused and only tries to apply it to one of them (in practice it doesn't apply it to either).

**Comment by samsinsane** [comment]
@redorav Unfortunately, Visual Studio only supports one version per project and they don't make that very clear. It's only obvious when you attempt to set it in two different configurations and it doesn't work.

**Comment by redorav** [comment]
I see. I tried to do it manually and it's just like you describe... what a shame. I wanted to be able to have a DX12+Win10 configuration without affecting other configurations which that actually compile in previous versions of Windows.

**Comment by redorav** [comment]
@samsinsane I tried playing with this a little bit more. From the Visual Studio options menu you can't change this property per project because it goes into the "Globals", but it seems that it can be done by tweaking the .vcxproj file. Typically properties go in the "Configuration" label, and conditionally setting the **WindowsTargetPlatformVersion** fixes this issue and allows different configurations to targets different Windows SDKs. I tested this in a small example project that included d3d12.h, which compiles when targeting Windows 10 and doesn't when targeting Windows 8 (which is my use case)

I don't know how premake creates the vcxprojs but it looks like it should be relatively easy to add. Here is what I did in the vcxproj to make this work.

```xml
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'" Label="Configuration">
    <ConfigurationType>Application</ConfigurationType>
    <UseDebugLibraries>true</UseDebugLibraries>
    <PlatformToolset>v141</PlatformToolset>
    <CharacterSet>MultiByte</CharacterSet>
    <WindowsTargetPlatformVersion>10.0.16299.0</WindowsTargetPlatformVersion>
</PropertyGroup>
```

**Comment by samsinsane** [comment]
@redorav Nice, glad there's an alternative!

> Should I create a new bug for this? I kind of feel like it's well suited here since it goes hand in hand with the targetplatformversion API

Creating a new bug would be great! This is actually a merged pull request, so we can't really "reopen" it or anything.

**Comment by redorav** [comment]
Ah. you're totally right, I've created https://github.com/premake/premake-core/issues/936 for this.

**Pull request merged**
