### PR TITLE
Add build steps to Visual Studio

### PR DESCRIPTION
**Pull request by redorav**
**What does this PR do?**

Adds build steps to Visual Studio through the buildcommands interface. (**edit:** See issue #1400 for more information and discussion).

**How does this PR change Premake's behavior?**

This adds missing functionality, to be able to have build steps with custom inputs and outputs

**Anything else we should know?**

**Did you check all the boxes?**

- [X] Focus on a single fix or feature; remove any unrelated formatting or code changes
- [x] Add unit tests showing fix or feature works; all tests pass
- [x] Mention any [related issues](https://github.com/premake/premake-core/issues) (put `closes #XXXX` in comment to auto-close issue when PR is merged)
- [X] Follow our [coding conventions](https://github.com/premake/premake-core/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] Minimize the number of commits

*You can now [support Premake on our OpenCollective](https://opencollective.com/premake). Your contributions help us spend more time responding to requests like these!*

### CODE REVIEW

**Comment by starkos** [comment]
I haven't tried, but I suspect that this encounter the same bug I just fixed in #1401. This should be allowed:

```lua
project "MyProject"
   buildcommands { "cmd.exe %{cfg.buildcfg.abspath}" }
```

If you're trying to process that command at the project level, it will fail because `cfg` will not be set. See #1013 for more discussion.

**Comment by redorav** [comment]
I just tested what you said and you're absolutely right, it works within the files filter but not at project scope. Why is it that project level commands cannot access configs? Is this something I can fix?

**Comment by starkos** [comment]
I'd be curious what `%{cfg.targetdir}` emits in that situation.

The relevant condundrum is: Premake allows you to specify settings in a "higher" scope (global, workspace, project) that get inherited by lower or narrower scopes (configuration, file). So when I use script like…

```lua
project "MyProject"
   buildcommands { "cmd.exe %{cfg.targetdir}" }
```

…my _intention_ is that a separate command would be created for _each configuration_ (think "Debug", "Release") in my project. I would expect that my project's debug configuration to use `cmd.exe bin/Debug`, for example, and release to use `cmd.exe bin/Release`.

I'm not sure what the right answer would be here. A new set of APIs might the easiest, but I'm open to more general-purpose suggestions.

**Comment by redorav** [comment]
As far as I can tell, this does the right thing in the case you describe. I have come up with the following:

configuration("Debug")
	targetdir ("MyTargetDir1")
		
configuration("Release")
	targetdir ("MyTargetDir2")

configuration {} -- Reset configurations so it applies to all

buildcommands
{
	"%{cfg.targetdir}"
}

And this expands the build command to ../../MyTargetDir1 only for Debug, and only MyTargetDir2 respectively on the Release configuration. It also respect configuration filters, so if I was to not have th configuration {} line, it only applies to Release.

**Comment by starkos** [comment]
Thanks for doing that research, I think this looks workable. If you could add some unit tests and squash the commits I think it should be good to approve.

Thanks for contribution!

**Comment by redorav** [comment]
I've added the unit tests and tried rebasing/squashing, but I'm making a mess like I did last time I tried doing the process. I think I conceptually understand what I'm trying to do, I just don't get how to do it with git...

**Comment by redorav** [comment]
I've kind of done it in a brute force way by rewinding the history and re-pushing the commits in one go, I need to learn how to properly do it.

**Comment by redorav** [comment]
Thanks for getting it in so quick, I love how premake keeps growing and maturing

**Pull request merged**
