### PR TITLE
Nvidia compiler support

### LINKED ISSUE #1874: Nvidia compiler support
**What problem will this solve?**
Add support for [Nvidia HPC C/C++ compiler](https://developer.nvidia.com/hpc-compilers).

**What might be a solution?**
Add a new toolset adapter for nvidia compiler in https://github.com/premake/premake-core/tree/master/src/tools 

**Anything else we should know?**
This is an important compiler in the world of HPC, as is Intel (#227).
I can try to make a PR for it.

### PR DESCRIPTION
**Pull request by abel0b**
**What does this PR do?**

Add a new toolset module for Nvidia HPC C/C++ compiler (Closes #1874).

**How does this PR change Premake's behavior?**

No breaking change.

**Anything else we should know?**

I only tested that the new toolset can compile premake on my linux machine using gmake2 exporter.

**Did you check all the boxes?**

- [x] Focus on a single fix or feature; remove any unrelated formatting or code changes
- [ ] Add unit tests showing fix or feature works; all tests pass
- [x] Mention any [related issues](https://github.com/premake/premake-core/issues) (put `closes #XXXX` in comment to auto-close issue when PR is merged)
- [x] Follow our [coding conventions](https://github.com/premake/premake-core/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] Minimize the number of commits
- [ ] Align [documentation](https://github.com/premake/premake-core/tree/master/website) to your changes

*You can now [support Premake on our OpenCollective](https://opencollective.com/premake). Your contributions help us spend more time responding to requests like these!*

### CODE REVIEW

**Comment by nickclark2016** [comment]
See #1874

**Comment by nickclark2016** [comment]
I'll review this when I have time to sit down and read through the entire toolset.  It's a wall of code, so it'll take me a while to get comfortable with it.

**Comment by abel0b** [comment]
For information, a large part of the code is copied from the gcc toolset. I tried to find an equivalent in the Nvidia compiler for each flag but it's not always possible.

**Comment by nickclark2016** [comment]
Sure, I don't expect equivalents to be there for everything. Do you mind posting a link to where you were referencing for the compiler flags just so I'm looking at the same sources as you when I review?

**Comment by abel0b** [comment]
Here is the latest available documentation for nvidia compiler : [NVIDIA HPC Compilers Reference Manual](https://docs.nvidia.com/hpc-sdk/compilers/hpc-compilers-ref-guide/index.html)

**Comment by Jarod42** [comment]
Should it be an external modules instead?

**Comment by nickclark2016** [comment]
Just poking the discussion on whether this should be an external module or a core module.

**Comment by nickclark2016** [comment]
Closing for now. If you decide to make it an external module, please either open a PR to add it to the modules list or ping me in an issue and I'll do it.

**Pull request closed without merging**
