### PR TITLE
Rearranged --start-group --end-group to enclose only the user libs.

### LINKED ISSUE #531: --start/end-group
Starting a separate topic here to debate this specific behaviour.

My original code used to produce:
```
LIBS += -Wl,--start-group workspacelib1.a workspacelib2.a -Wl,--end-group -lsyslib1 -lsyslib2
```
The logic was that cross-dependencies may exist between the users libs within the workspace, and the system libs would appear after (ie, not having cross-dependencies).

The new behaviour with `linkgroups 'On'` produces:
```
LIBS += -Wl,--start-group workspacelib1.a workspacelib2.a -lsyslib1 -lsyslib2 -Wl,--end-group
```
And this new link line causes our build to fail for some reason. In our case, Qt libs are among those system libs, and they don't seem to like being bundled into the link group. We just see unresolved externals for all Qt symbols.

I think my original behaviour was correct. Is there a reason it was changed to wrap everything?

### PR DESCRIPTION
**Pull request by TurkeyMan**
resolve #531

### CODE REVIEW

**Comment by samsinsane** [comment]
LGTM, is the `nogroups` parameter for modules to override the grouping?

**Comment by starkos** [comment]
I do remember this logic being in the code—weird that it get stepped on.

I'm also a bit confused by the purpose of `no groups` when `cfg.linkgroups` is already there?

**Comment by TurkeyMan** [comment]
Well, since I'm removing the function `getlinksonly` (which was never called incidentally), I figured I should retain functionality that function provided, which is to emit a link line but without the grouping tabs in it... maybe that's not useful (I wonder why `getlinksonly` existed)? I can remove it...?

**Comment by TurkeyMan** [comment]
> is the nogroups parameter for modules to override the grouping?

Sure... sounds good! :)

**Comment by TurkeyMan** [comment]
Resolves #531 (<-- does this work on github?)

**Comment by TurkeyMan** [comment]
fixes #531 (where do you type this on github?!)

**Comment by tvandijck** [comment]
> Well, since I'm removing the function getlinksonly (which was never called incidentally), 

not true.. before this commit we had this code:
```lua
function gcc.getlinks(cfg, systemonly)		
		local result = gcc.getlinksonly(cfg, systemonly)
```

it was introduces in a previous commit to try and reuse as much code as possible between gcc and clang... clang on Mac does not like the linkgroups in xcode 6.0, so we needed it to not be there.

Now, obviously as we moved forward, and found out that it is probably better to allow a user to switch it on/off with a proper API... this kind of got reverted somewhat. I guess when I did make the changes I never really realized that system libs should not be included. Our game builds fine with it, so it never was a problem either... 

Your changes however look fine to me, we should probably merge it, as it gets us back closer to the original, while still maintaining the new linkgroups api... so that will be sufficient for our use-cases.

**Comment by starkos** [comment]
Where are we at with this one? Safe to merge?

**Comment by TurkeyMan** [comment]
I think that was an LGTM from tom?

**Pull request merged**
