### PR TITLE
fix targetdir default.

### PR DESCRIPTION
**Pull request by tvandijck**
https://github.com/premake/premake-core/issues/136

### CODE REVIEW

**Comment by starkos** [comment]
LGTM but tests are failing?

**Comment by tvandijck** [comment]
yeah, a lot of tests are actually testing against "./".
I'll submit fixes...

**Comment by TurkeyMan** [comment]
Aye, LGTM (except CI fail). I've experienced this issue recently.
Nice one!

**Comment by tvandijck** [comment]
So I fixed all the unit-tests I can fix... the xcode module is so annoying though.... I don't have that, and to try and fix that I would need to fork it, update the submodule file to correctly point to it, and then make the branch use it.... which isn't a mergable action.... Any suggestions?? this whole sub-module business is a PITA.... I hate it...

**Comment by starkos** [comment]
Hmm…so now I'm thinking the CI server shouldn't be unit testing the modules, otherwise we're going to end up with a chicken-and-egg problem where you can't update core because the modules don't reflect the necessary changes, and we don't want to change the modules because they will break until core is updated.

The right development sequence would be to make the changes to core, and then to update the modules to catch up.

We don't currently have CI enabled for the module repositories—that would actually be super useful. I didn't do the CI setup so I'm not actually sure what's involved.

> to try and fix that I would need to fork it, update the submodule file to correctly point to it, and then make the branch use it

FWIW I'm working against the same setup, and pushing to multiple repositories. It is certainly less convenient but it hasn't been anything major. I don't update submodules or any of that. I have my own fork of premake-xcode set up as a second remote on the submodule. I make my changes on a local branch in the submodule, push it to my second remote, and then submit a pull request on it. You just have to take care *not* to update the submodule reference in premake-core; the core maintainers can take care of doing that when they (okay, mostly me) accept the request.

I'm not completely opposed to moving everything into core, but let's open a discussion somewhere else about that.

**Comment by starkos** [comment]
I've merged this and fixed up all the tests.

**Pull request merged**
