### PR TITLE
Support toolset prefix in filters.

### PR DESCRIPTION
**Pull request by tritao**
Tries to fix issue #257.

This is not passing the tests locally, I've spent some time trying to track it down, I guess I messed up the code somewhere but I'm not very familiar with this part of Premake.

Any ideas @starkos?

### CODE REVIEW

**Comment by starkos** [comment]
I'm not seeing anything immediately wrong. I'll have to pull it later and take a look. Could be a side effect from other tests that needs to be cleared out by the test framework between runs?

**Comment by samsinsane** [comment]
I think it's [this line](https://github.com/premake/premake-core/blob/master/tests/testfx.lua#L149), `#expected` will be `1` while `#actual` will be `0`, then it falls into the next block which will iterate over the pairs in `expected` and assume that `actual` is of the same size, which results in `nil` being passed down into the next function. The line I linked just needs to be changed to `~=` and it should pass the tests again. :)

**Comment by samsinsane** [comment]
Ignore my previous comment, I misunderstood what was wrong. I think there's still an issue in the function I linked, this test case should have failed instead of producing an error in the testfx file. Regardless, the issue is that `prepare` doesn't update `prj` to the filtered version, it's still the original. You'll need to either add the filter into `p.project.bake` in `oven.lua` (if it's a valid thing to do @starkos?) or iterate through the `wks.configs` and find the config that was baked in `oven.bakeConfigs(wks)`.

Hopefully this sorts the PR out and we can merge it in soon :)

**Comment by starkos** [comment]
> Regardless, the issue is that prepare doesn't update prj to the filtered version

That's close. The project settings don't take the toolset into account, only configurations do. So you will have to modify the setup to look like:

```lua
	local wks, prj, cfg

	function suite.setup()
		wks, prj = test.createWorkspace()
	end

	local function prepare()
		cfg = test.getconfig(prj, "Debug")
	end
```

And then replace `prj.defines` with `cfg.defines` everywhere.

**Comment by Trass3r** [comment]
Nice, works for me so far!

**Comment by JohannesMP** [comment]
Seems to work. Looking forward to hopefully seeing it in future builds.

**Comment by samsinsane** [comment]
@tritao have you had a chance to make the change that @starkos mentioned? Once that test is working, this should be good to merge.

**Pull request merged**
