### PR TITLE
Fix Nuget package handling to support Unix-style paths

### PR DESCRIPTION
**Pull request by tritao**
Fixes Nuget package handling to work on OSX.

cc @aleksijuvani

### CODE REVIEW

**Comment by aleksijuvani** [comment]
LGTM, except that the current NuGet tests are in `test_assembly_refs.lua` so we should either move those tests to this new file or move this new test to that file.

**Comment by aleksijuvani** [comment]
Also, just to note – this is matching the filenames returned by the NuGet API so the host system shouldn't matter.. the packager just used a Unix system so that's why the slashes are different.

**Comment by tritao** [comment]
I thought so too, but actually the issue is some `path.translate` call that is done before this function is called, only realized this after the fix, what do you think? Should we hardcode a separator in the translate call instead?

**Comment by aleksijuvani** [comment]
You're right, it looks like the API always returns paths with forward slashes, so it is a local issue after all. Hardcoding it to use the "\\" separator might be the best course of action. I think this is what Visual Studio expects anyway.

**Comment by tvandijck** [comment]
I'm a little confused with the conclusion of the above discussion? are we good to merge? it looks fine to me.

**Comment by aleksijuvani** [comment]
Should be good to merge, I just got a bit confused.

**Comment by tritao** [comment]
👍

**Pull request merged**
