### PR TITLE
Recognize more situations where '..' should not be trimmed.

### PR DESCRIPTION
**Pull request by tvandijck**

### CODE REVIEW

**Comment by starkos** [comment]
Would it be possible to get some tests for these? Several people have been modifying this function, and it would be easy to regress!

**Comment by tvandijck** [comment]
@Bekenn James, any chance you have time for that?

**Comment by Bekenn** [comment]
Sure, I should be able to take care of that over the weekend.

**Comment by starkos** [comment]
Thanks! I'm hoping to be able to crank through all your new pull requests this weekend.

**Comment by starkos** [comment]
Cool, thanks…sorry for running so far behind here.

**Comment by tvandijck** [comment]
no worries, if you need any help with anything, just let us know...

**Pull request merged**
