### PR TITLE
Set default toolsets for vs2005 and vs2008.

### PR DESCRIPTION
**Pull request by tvandijck**

### CODE REVIEW

**Comment by tvandijck** [comment]
hmmm, interesting side effect 👎

**Comment by tvandijck** [comment]
Question @starkos & @samsinsane do we wish to maintain the vs2005 and vs2008 backends? I no longer have access to it.. it's going to be increasingly difficult to do the right thing for these.

**Comment by samsinsane** [comment]
I, personally, don't care either way, though I don't think VS2008 is EoL yet, so perhaps the removal should wait until then?

**Comment by tvandijck** [comment]
https://blogs.msdn.microsoft.com/visualstudio/2017/04/10/end-of-support-for-visual-studio-2008-in-one-year/

April 10, 2018 apparently... We can wait...

**Pull request merged**
