### PR TITLE
Languages fixes

### PR DESCRIPTION
**Pull request by tvandijck**
So this is just one possible solution to the language issues explained here:
https://github.com/premake/premake-core/issues/770

Basically it's a set of changes that allows fields to decide how they get stored or merged when accessed. The tests test just a few use-cases that I could think of, more might be needed to fully cover everything, help appreciated.

### CODE REVIEW

**Comment by tvandijck** [comment]
FYI, this goes the route of ```C++``` does not override ```C++11``` when set, but ```C++11``` would override ```C++14```. Basically, if you are not specific, then it won't set it if something more specific is set. If you set a different language entirely, it will set it regardless of whether you are specific or not.

**Comment by tvandijck** [comment]
> but as I said in #770, I think there should always be a way to tell Premake to not emit anything.

@samsinsane which is currently not possible at all... there is no "removelanguage" API, and premake sets language to "C++" at startup... so unless you set it to something else, it will be "C++".

We can remove the default, for sure... but then this will fail:
https://github.com/premake/premake-core/blob/master/src/base/validation.lua#L206

which we could remove... but then this will no longer work:
https://github.com/premake/premake-core/blob/master/src/actions/vstudio/vs2010.lua#L52

which we could fix, but not using language as the project type, as you suggested, but then you basically just end up with: ```language``` & ```dialect``` api's, maybe with different names ```projecttype``` & ```language```, same difference, with same problems...

So... as it stands, there is currently no way to have premake NOT emit 'language', this PR does not change that... The "compileas" PR fixes the "CompileAs" emit issue separately, which would still be needed with this PR.

If we wanted to remove language default, then we need to figure out a different way to emit language and project types, which is a much bigger change. But... I'm open to suggestions obviously..

**Comment by samsinsane** [comment]
> which is currently not possible at all... there is no "removelanguage" API, and premake sets language to "C++" at startup...

This PR is designed to stop C++ from overriding C++11. What standard was it emitting to the command line? I was under the assumption that it was not emitting any standard? Which is exactly what I think should happen, or at least be an option.

**Comment by tvandijck** [comment]
@samsinsane correct... it assumes that if a higher power sets a standard, then that higher power wins... just like with the flag...
```lua
workspace 'foo'
    language 'C++11'
    project 'x'
        language 'C++'
```
project 'x' gets C++11, because the workspace says so... just like
```lua
workspace 'foo'
    flags { 'C++11'}
    project 'x'
        language 'C++'
```
would have...

Which isn't to say we can't do anything else... but we have a ton of projects that relied on the behavior of the flag that way... The only way to basically not get this behavior without this PR, is to not set language anywhere, and assume someone else higher up (workspace?) sets it, and you only overload it if you want something different....

**Comment by samsinsane** [comment]
Correct, but how would you now do `removeflags { "C++11" }` at the project level?

**Comment by tvandijck** [comment]
That is a valid question indeed... 
You could write:
```
language 'C99'
language 'C++'
```
switch it to a different language, and then back, which would override it... but that is probably the dirtiest workaround I've ever posted here ;)

we could do something like:
```
language 'force:C++'
```

I'm not sure... it seems we're a little bit in a bind though... we want this behavior:
```
workspace 'foo'
    flags { 'C++11'}
    project 'x'
        language 'C++'
```

but we also want:
```
workspace 'foo'
    flags { 'C++11'}
    project 'x'
        language 'C++'
        removeflags { 'C++11' }
```

with this PR, the first is working:
```
workspace 'foo'
    language 'C++11'
    project 'x'
        language 'C++'
```

but the second is no longer available without a dirty.
without this PR, the first isn't working, but the second case is.

**Comment by samsinsane** [comment]
Yeah, that's my only concern really, that we don't support both. I am not against your changes, I'm just against trading one for the other.

Perhaps, the force prefix could be used for your use case? You're forcing the dialect/standard to hold, though, I'm forcing the dialect/standard to drop. Though, your use case would require force to be stored, and then later removed in the oven. Hmm, either way I'm happy with the idea of the prefix, there could be a better solution, I can't think of anything right now though.

Anyone got ideas on how to achieve both cases relatively cleanly?

**Comment by tvandijck** [comment]
closing this, I don't think this is the answer, although I think the "processed" field kind is kinda cool...

**Pull request closed without merging**
