### PR TITLE
use rpaths & soname/install_name to link sibling shared libraries

### PR DESCRIPTION
**Pull request by noresources**
…on OS X and Linux

new api runpathdirs().
	<toolset>.getrunpathdirs() adds user defined rpath set using runpathdirs().
	handle runpathdirs in gcc, clang and snc.

make.list() can now add quotes to list elements

### CODE REVIEW

**Comment by TurkeyMan** [comment]
Given a quick once-over, this LGTM, but I haven't given this enough time to say that with confidence.
I need this patch at work, so if nobody reviews this before me, I'll give it a shot at work when I get a moment to work on our linux build...

**Comment by starkos** [comment]
If you could that would be great, most of my projects are VS and Xcode these days, I don't have many good examples to try it on.

**Comment by tritao** [comment]
This is also biting us on https://github.com/mono/CppSharp.

**Comment by ddobrev** [comment]
Can we download the binaries from the build for this pull - https://travis-ci.org/premake/premake-core/builds/82604919 ? We really need this fix.

**Comment by tritao** [comment]
Re-discovered this issue again today after some shared library loading problems on OSX.

Thinking again about this it seems this pull would be an improvement over the current behavior, can this be merged? It can always be reverted if it breaks something.

**Comment by tritao** [comment]
Updated the pull for recent Premake master: https://github.com/premake/premake-core/pull/568

Tested on my project and works fine.

**Comment by tvandijck** [comment]
Merged: #568 instead.

**Pull request closed without merging**
