### PR TITLE
sort file lists

### PR DESCRIPTION
**Pull request by bmwiedemann**
because filesystems return files in random order
and linkers order functions depending on order of .o files

This helps enable reproducible builds in software built with premake
like [0ad](https://play0ad.com/)

See https://reproducible-builds.org/ for why that matters.

### CODE REVIEW

**Comment by starkos** [comment]
Are you sure about this? I thought Premake already sorted all lists under the hood.

**Comment by tvandijck** [comment]
@starkos it does: https://github.com/premake/premake-core/blob/master/src/base/oven.lua#L671

**Comment by starkos** [comment]
Okay, closing this as unnecessary then. Feel free to reopen if there is something I've not considered!

**Comment by bmwiedemann** [comment]
OK. then maybe 0ad is bundling an older version of premake.

**Comment by tvandijck** [comment]
https://trac.wildfiregames.com/wiki/premake

Note: Currently we bundle a modified version of the Premake 4.3 release, located in build/premake/premake4. The modifications fix a number of bugs and missing features in the 4.3 release.

**Comment by tvandijck** [comment]
Also looks like there is an effort to upgrade to Premake5 here: https://trac.wildfiregames.com/ticket/3729

**Pull request closed without merging**
