### PR TITLE
intrinsics api.

### PR DESCRIPTION
**Pull request by tvandijck**
adding:
```lua
instrinsics 'On' or 'Off'
```

### CODE REVIEW

**Comment by TurkeyMan** [comment]
Doesn't emit option to makefile

**Comment by TurkeyMan** [comment]
Is it the case that this one doesn't have an off state?

**Comment by tvandijck** [comment]
Yeah, I looked for one, but while there is a "No" in the Visual Studio IDE, I couldn't find a command line option to make it do the same thing... it didn't accept /Oi-

**Comment by TurkeyMan** [comment]
What does the VS command line look like if you select "No" in the property grid?

**Comment by samsinsane** [comment]
> What does the VS command line look like if you select "No" in the property grid?

From the test I just did, nothing is added. This is Premake without it set:
```
/MP /GS /TC /analyze- /W4 /Zc:wchar_t 
/I"contrib\lua\src" /I"contrib\zlib" /I"contrib\libzip" /I"contrib\curl\include" /ZI /Gm- 
/Od /Fd"obj\Debug\Premake5\vc140.pdb" /Zc:inline /fp:precise 
/D "PREMAKE_COMPRESSION" /D "CURL_STATICLIB" /D "PREMAKE_CURL" /D "_DEBUG" /D "_CRT_SECURE_NO_DEPRECATE" /D "_CRT_SECURE_NO_WARNINGS" /D "_CRT_NONSTDC_NO_WARNINGS" /D "_UNICODE" /D "UNICODE" 
/errorReport:prompt /WX- /Zc:forScope /RTC1 /Gd 
/Oy- /MTd /Fa"obj\Debug\Premake5\" /EHsc /nologo 
/Fo"obj\Debug\Premake5\" /Fp"obj\Debug\Premake5\premake5.pch"
```

With it set to `Yes`:
```
/MP /GS /TC /analyze- /W4 /Zc:wchar_t 
/I"contrib\lua\src" /I"contrib\zlib" /I"contrib\libzip" /I"contrib\curl\include" /ZI /Gm- 
/Od /Fd"obj\Debug\Premake5\vc140.pdb" /Zc:inline /fp:precise 
/D "PREMAKE_COMPRESSION" /D "CURL_STATICLIB" /D "PREMAKE_CURL" /D "_DEBUG" /D "_CRT_SECURE_NO_DEPRECATE" /D "_CRT_SECURE_NO_WARNINGS" /D "_CRT_NONSTDC_NO_WARNINGS" /D "_UNICODE" /D "UNICODE" 
/errorReport:prompt /WX- /Zc:forScope /RTC1 /Gd 
/Oy- /Oi /MTd /Fa"obj\Debug\Premake5\" /EHsc /nologo 
/Fo"obj\Debug\Premake5\" /Fp"obj\Debug\Premake5\premake5.pch" 
```

With it set to `No`:
```
/MP /GS /TC /analyze- /W4 /Zc:wchar_t 
/I"contrib\lua\src" /I"contrib\zlib" /I"contrib\libzip" /I"contrib\curl\include" /ZI /Gm- 
/Od /Fd"obj\Debug\Premake5\vc140.pdb" /Zc:inline /fp:precise 
/D "PREMAKE_COMPRESSION" /D "CURL_STATICLIB" /D "PREMAKE_CURL" /D "_DEBUG" /D "_CRT_SECURE_NO_DEPRECATE" /D "_CRT_SECURE_NO_WARNINGS" /D "_CRT_NONSTDC_NO_WARNINGS" /D "_UNICODE" /D "UNICODE" 
/errorReport:prompt /WX- /Zc:forScope /RTC1 /Gd 
/Oy- /MTd /Fa"obj\Debug\Premake5\" /EHsc /nologo 
/Fo"obj\Debug\Premake5\" /Fp"obj\Debug\Premake5\premake5.pch" 
```

The second last line is where it appears to slot in.

**Pull request merged**
