### PR TITLE
fixed a crash when a token contains non-escaped backslashes

### PR DESCRIPTION
**Pull request by dcourtois**
If you use a token containing a non-escaped backslash (e.g. "%{cfg.linktarget.directory:gsub('/', '\\\\')}" then the detoken function will crash with the following error "unfinished string near '<eof>'". This is due to the fact that even though the backslash is escaped, once sent to the loadstring function, there is only one backslash left, thus the crash.

This pull request simply adds a unit test for this case (which I use in almost all my scripts, and which worked fine until recently, oddly enough ..) and the fix simply consists on escaping again any backslashes.

### CODE REVIEW

**Comment by dcourtois** [comment]
Someone can take a look at this ? There's a workaround that consist on double escaping backslashes, but it's a bit tedious :p

**Comment by TurkeyMan** [comment]
Fixes relating to escaping always make me super-nervous! ;)
Your fix looks contained, I can't imagine how it can go wrong, so, LGTM.

**Comment by starkos** [comment]
Yes, me too, which is why this hasn't landed yet. Hoping to run it through all my client projects this weekend to check for side effects.

**Comment by dcourtois** [comment]
My description was a bit erroneous : github escaped my example ^^'' (basically the "e.g." thing in my first comment just crash when it shouldn't :p)

**Comment by starkos** [comment]
Okay, sorry for the delay, finally got a chance to try it. The issue I'm seeing is that we have lots of commands that are already properly escaped:

```lua
buildcommands { '"$(MY_SDK_DIR)\\host_tools\\bin\\toolname.exe" "%(FullPath)" -o "$(IntDir)%(Filename).x"' }
```

This did generate (correctly):

```xml
"$(MY_SDK_DIR)\host_tools\bin\toolname.exe" "%(FullPath)" -o "$(IntDir)%(Filename).x"
```

With this change it generates (incorrectly):

```xml
"$(MY_SDK_DIR)\\host_tools\\bin\\toolname.exe" "%(FullPath)" -o "$(IntDir)%(Filename).x"
```

Which points out the *real* reason for your crash: '\\' is equivalent to one backslash, not two. `gsub("one/two/three", "/", "\\")` results in "one\two\three" and not "one\\two\\three" as I think you were expecting.

My thought is that Lua requires backslashes to be escaped in strings, and that this isn't an uncommon requirements. I think in this case the bug was in your own code. Perhaps Premake should output a nicer error message, but otherwise I don't think this is something that should be "fixed" (I may way to use an escaped character code here, after all, though I can't think of a good reason for it off the top of my head…outputting formatted text into a file perhaps?)

I vote to close. Any one else have thoughts on this?

**Comment by dcourtois** [comment]
Hi,
Maybe I wasn't specific enough, but the bug is only for tokens ! It's not a problem with escaping characters in general, it's a real problem due to the way detoken works. What happens is this (with tokens) :

1. In Lua, you have a string like this: "%{cfg.linktarget.directory:gsub('/', '\\')}"
2. In premake, it becomes expanded to this: "return cfg.linktarget.directory:gsub('/', '\')"
3. And then the loadstring is executed, e.g. loadstring("return cfg.linktarget.directory:gsub('/', '\')") which is invalid.

The example you provided with build commands do not have the problem of the tokens since the string are just passed through to the end tool, so the usual escape works. But for tokens, the string is "interpreted" twice, leading to this problem.

**Comment by starkos** [comment]
That second snippet I posted is an actual result after applying this pull request. The extra escaping is not currently being limited to token expansions.

**Comment by dcourtois** [comment]
Ah yes you're right. I'll add your example as a unit test and modify my PR to ensure that only the inside of a token gets correctly escaped. Thanks for taking the time to check this :)

**Comment by dcourtois** [comment]
I updated the pr: now it only escapes what's inside a token (e.g. what's passed to the "loadstring" function) and doesn't modify the rest. I added another unit test to ensure of that.

**Comment by starkos** [comment]
Looks better, thanks!

**Pull request merged**
