### PR TITLE
Added MonoDevelop/Xamarin submodule.

### PR DESCRIPTION
**Pull request by TurkeyMan**
The MonoDevelop plugin is fairly mature. It'd be nice to make it available as part of the standard build.
Obviously I accept full responsibility servicing bug-reports for this submodule.

### CODE REVIEW

**Comment by starkos** [comment]
Sorry, I'm still trying to get caught up from the travel. I'm planning to set aside a little time this weekend to crank through more of these requests; I'll make sure I look at these.

**Comment by TurkeyMan** [comment]
No rush, I just thought I'd put this here.
If it's not to be considered for inclusion-proper, then I'll move the repos to my own namespace.

**Comment by starkos** [comment]
I'm good with merging this, it just needs to be rebased.

**Comment by TurkeyMan** [comment]
Is rebased

**Pull request merged**
