### PR TITLE
Windows CI

### PR DESCRIPTION
**Pull request by TurkeyMan**
CI for windows. This is pending finding a good apt source for libole32 that travis doesn't reject.

### CODE REVIEW

**Comment by starkos** [comment]
Any thoughts on this one? No worries if not, I'm just trying to tidy up the open pull requests.

**Comment by TurkeyMan** [comment]
Oh yeah, I just needed to chase down a package containing libole32.a that's available to travis. Or alternatively, commit that lib to the repo (I didn't want to do this).
Leave this here for the moment, I'll try and get back to it soon. Been busy lately.

**Comment by starkos** [comment]
Any word on this one? Or can I close it for now and open a new one later?

**Comment by TurkeyMan** [comment]
It's a good reminder. Every couple of days I think "shit I really need to do that!" and then get pulled to other things. I'll make it happen when I get a moment to stuff around with it.
I might commit the windows libs to the repo; the trouble was sourcing the windows libs from the package manager under Travis's environment, the linux distro seemed to have some strange package conflicts.

**Pull request closed without merging**
