### PR TITLE
os.execute windows path separator fix

### PR DESCRIPTION
**Pull request by akaStiX**
Fix for a https://github.com/premake/premake-core/issues/316

### CODE REVIEW

**Comment by akaStiX** [comment]
I am looking at the tests that failed and I don't understand, why do we need those trailing spaces in tokenized commands?!

**Comment by samsinsane** [comment]
If I recall correctly, I added those tests for an implementation that was then proven to not work in all situations. An alternative was provided and I must've forgotten to remove the tests, you can remove the tests with `_ExtraSpace` in them as they don't test anything.

**Comment by samsinsane** [comment]
I was slightly incorrect with my previous comment, those tests actually do something. They ensure the `IF EXISTS {dir}\\` check doesn't have a space between `{dir}` and `\\`, you can probably just adjust the `xcopy` parts to not contain the extra space.

**Comment by tritao** [comment]
Ping, what's the status on this fix?

**Comment by tvandijck** [comment]
1362 tests passed, 5 failed

**Comment by tritao** [comment]
I can see there's some failures, but as far as I can tell it's just meaningless whitespace?

```
before: IF EXIST a\ (xcopy /Q /E /Y /I a  > nul) ELSE (xcopy /Q /Y /I a  > nul)
after: IF EXIST a\ (xcopy /Q /E /Y /I a > nul) ELSE (xcopy /Q /Y /I a > nul)
```

**Comment by starkos** [comment]
Failing tests are failing tests. Either we need to fix the implementation to pass the tests, or adjust the tests to match the implementation (if the whitespace really is meaningless).

**Comment by akaStiX** [comment]
I am sorry guys for a huge delay, I'll fix my pull requests

**Comment by tritao** [comment]
Thanks @akaStiX.

**Comment by samsinsane** [comment]
As I mentioned above, these tests are valid but the xcopy parts don't need to have the extra space. It only ensures that `IF EXISTS a\` isn't `IF EXISTS a \`.

Additionally, it seems it would be better if each token command dictated whether or not the arguments needed to be normalized, for example, this would break `echo https://github.com` (basically what was reported in #279 for `os.execute`) which would emit `echo https:/github.com`. Also, while we only have file system commands in here, if we (or a module) added support for things such as `wget`/`curl`, this will definitely break those as they rely on URLs.

Other than that, this LGTM once the tests expected values are fixed to not have the extra whitespace. Thanks @akaStiX!

**Comment by tvandijck** [comment]
@akaStiX what is the status on this PR? do we want it merged, in which case we would really like to see it fixed... otherwise it's just going to sit here and wait for fixes.

**Comment by samsinsane** [comment]
Closing this in favour of #570.

**Pull request closed without merging**
