### PR TITLE
Disable XP deprecation warning for Visual Studio projects

### PR DESCRIPTION
**Pull request by withmorten**
Related issue: https://github.com/premake/premake-core/issues/1438

### CODE REVIEW

**Comment by withmorten** [comment]
Looks like all the tests are failing (should have thought of that) - perhaps it at least should only be added to Windows projects (and I should maybe move it to the bottom of the globals list)?

**Comment by samsinsane** [comment]
You should definitely ensure it only happens on Windows (`os.target() == p.WINDOWS`) but also you should ensure that it only happens for VS2019 (your issue mentions that it only started in VS2019), if this continues in VS2021 it can be updated to include that but we shouldn't have this happening when XP support is completely gone. Additionally, you should move the entry to the bottom of the group, you're going to break a lot of unit tests by putting it at the top. Once you've done this, I highly recommend you write unit tests to ensure that it doesn't happen in VS2017 or when `system "android"`, and that it does happen in VS2019.

**Comment by samsinsane** [comment]
@withmorten thanks for the additional context on that!

**Comment by withmorten** [comment]
The final result then looks like this, instead of adding it to the Globals, it gets added to the Configuration specific parts:

      <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'" Label="Globals">
        <XPDeprecationWarning>false</XPDeprecationWarning>
      </PropertyGroup>
      <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|Win32'" Label="Globals">
        <XPDeprecationWarning>false</XPDeprecationWarning>
      </PropertyGroup>
      <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='ReleaseNO|Win32'" Label="Globals">
        <XPDeprecationWarning>false</XPDeprecationWarning>
      </PropertyGroup>`

That's okay?

**Comment by samsinsane** [comment]
> That's okay?

Seems good to me :+1:

**Comment by withmorten** [comment]
Okay, now it only sets the warning to false when specifically choosing v141_xp, and only per config!

I hope the way I added the tests (one for global, one for specific config "Release" only) is okay!

**Pull request merged**
