### PR TITLE
Fix VS2013 and older always rebuilding when debug symbols explicitly …

### PR DESCRIPTION
**Pull request by jstewart-amd**
…disabled

Visual Studio versions 2013 and older have an issue with
DebugInformationFormat set to None. The project will always be out of
date and thus always rebuild. The workaround is to leave the
DebugInformationFormat field blank.

https://connect.microsoft.com/VisualStudio/feedback/details/833494/project-with-debug-information-disabled-always-rebuilds

VS2015 and newer do not have this issue.

### CODE REVIEW

**Comment by jstewart-amd** [comment]
I added a new test, so now there are separate tests for pre-VS2015 (leave the field blank) and VS2015 and later (using None works as expected).

**Comment by jstewart-amd** [comment]
More information about the underlying issue in Visual Studio can be found here:

Project with debug information disabled always rebuilds
https://connect.microsoft.com/VisualStudio/feedback/details/833494/project-with-debug-information-disabled-always-rebuilds

"The issue you are seeing is because the specific code incorrectly doesn't check for None. It looks for OldStyle and Empty."

"You can workaround it by blanking out the property field. It will be passed to the build as an empty string and correctly by pass the 'Forcing recompile'."

**Comment by jstewart-amd** [comment]
.\bin\release\premake5.exe test
Running action 'test'...
1475 tests passed, 0 failed in 1.97 seconds

**Comment by samsinsane** [comment]
I kind of feel like this was recently changed to be the way it is. Are all the files that are generated by the various versions of visual studio, *exactly* the same with and without this PR? I'm a little hesitant to approve a PR that could just be reverted in a few weeks/months because *something* is different.

> .\bin\release\premake5.exe test
> Running action 'test'...
> 1475 tests passed, 0 failed in 1.97 seconds

Thanks for this, but it's not necessary as the build scripts perform these checks when you create your PR. 😃

**Comment by tvandijck** [comment]
LGTM too... won't affect us...

**Comment by jstewart-amd** [comment]
Thanks, everybody. I wasn't ignoring @samsinsane. Rather, I was doing more testing.

To clarify, Premake without this fix is not producing incorrect output for VS2012 and VS2013. But it is running into a Visual Studio bug. The bug manifests when explicitly setting debug symbols to "Off". The symptom is that Visual Studio always thinks the project is out of date and so always does a full recompile (for the build configs where you have explicitly disabled symbols).

The issue showed up in the switch from `flags { "Symbols" }` to the new `symbols` function. Prior to the
`symbols` function, there was no notion of explicitly disabling symbols. You either had `flags { "Symbols" }` or you didn't. Absence of `flags { "Symbols" }` was an implicit disable.

This PR is a workaround for the Visual Studio bug, following the suggestion from Microsoft in the connect.microsoft.com link mentioned in a previous comment.

For VS2010, Premake actually **is** producing incorrect output when symbols are explicitly disabled. VS2010's DebugInformationFormat does not have a None setting. The result is this error:
`error : Element <DebugInformationFormat> has an invalid value of "None".`

This PR also fixes the VS2010 issue.

Summary:
* VS2010 - Does not support DebugInformationFormat None. Leave field blank to get the behavior of None.
* VS2012/VS2013 - Supposedly supports DebugInformationFormat None, but it doesn't work. Leave field blank to get the behavior of None.
* VS2015 and newer - DebugInformationFormat None actually works.

I have tested on VS2010, VS2012, VS2013, and VS2015. I still don't have VS2017 installed anywhere, but output produced for VS2015 and newer is unchanged by this PR.

**Comment by tvandijck** [comment]
I verified correct behavior in VS2017....

**Comment by samsinsane** [comment]
Sounds good to me, thanks for the fixes!

**Pull request merged**
