### PR TITLE
pic api

### PR DESCRIPTION
**Pull request by TurkeyMan**
Added PIC (position independent code) flag, used all over the place.

### CODE REVIEW

**Comment by TurkeyMan** [comment]
TODO: support the PIC flag for GCC/Clang builds.
This is here to sample for objections first...

**Comment by starkos** [comment]
IMO this would be better as a pic() (or similar) API call because a) flags aren't the best for usability (overlapping or removing values) and I'd like to trend away from them and b) I think there are actually a few different kinds of position independent code ("pic" vs. "PIC", relaxed, simple) that we may want to support in the future.

I'd suggest a simple pic ( "On" | "Off" ) for starters?

**Comment by TurkeyMan** [comment]
Yeah, I wasn't feeling convinced either way.
I'll change it and implement for clang/gcc.

**Comment by TurkeyMan** [comment]
Okay, I changed it to a pic api, updated the code, tested it works, unittests pass.
I'm not sure why travis didn't rebuild my PR when I amended... but it does build and passes the unittests.

**Comment by starkos** [comment]
Cool—can you add a page to the wiki? Thanks!

**Pull request merged**
