### PR TITLE
add zip.extract(src, dst) method.

### PR DESCRIPTION
**Pull request by tvandijck**

### CODE REVIEW

**Comment by tritao** [comment]
Looking good, I'm excited to finally be able to use these APIs for package management.

**Comment by tvandijck** [comment]
Yeah, I would love for someone else to extend this further... we're only really using the extract here, but I can imagine a "compress" method would be nice too.. one that takes a folder name, and a zip name.

**Comment by tvandijck** [comment]
ok, finally... all tests pass... I was screwing up the recursive mkdir...

**Comment by starkos** [comment]
This is great, thanks!

**Pull request merged**
