### PR TITLE
Add support for .swift file for xcode

### LINKED ISSUE #667: Can this tool be updated to include and create .swift files?
I quickly scanned some source under the Xcode support and didn't see anything. Just wondering whether it's possible and planned to support Xcode projects using Swift (.swift) files?

### PR DESCRIPTION
**Pull request by sp-rafael-lecina**
**What does this PR do?**
 - Set swift files as source code
 - Adds a ``swiftversion`` to be able to configure Swift Language Version

**How does this PR change Premake's behavior?**
 - Adds ``.swift`` on the file extension lists with proper values
 - Adds a DSL api to set the SWIFT_VERSION setting

Are there any breaking changes? Will any existing behavior change?
 - No

**Anything else we should know?**

Add any other context about your changes here.
 - closes #667

**Did you check all the boxes?**

- [x] Focus on a single fix or feature; remove any unrelated formatting or code changes
- [x] Add unit tests showing fix or feature works; all tests pass
- [x] Mention any [related issues](https://github.com/premake/premake-core/issues) (put `closes #XXXX` in comment to auto-close issue when PR is merged)
- [x] Follow our [coding conventions](https://github.com/premake/premake-core/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] Minimize the number of commits

### CODE REVIEW

**Comment by starkos** [comment]
This looks like a nice feature addition, thanks for taking the time! Unfortunately, it looks like you've broken some of the existing unit tests with your changes—we need all tests to be passing before we can merge your change.

It might make things easier if you split your changes up into two PRs: one that adds Swift support, and another for the single value fix. The Swift changes should pass the existing tests with no trouble, but you will probably need to fix up some of them in order to pass your single value changes.
 
It would also be helpful if you could add a new test or two to cover your improvements, verify they work, and protect against any future regressions.

And a small GitHub tip: If you put "Closes #667" instead of "There was already an issue about this: #667" that issue will get closed automatically as soon as your PR merges.

You can push new commits to this branch to patch things up, or close this one and open new one(s). Seem reasonable?

**Comment by sp-rafael-lecina** [comment]
Thanks
Once I have some time I'll do the fixes you suggest

Just one question. Do you know why the single value code was commented?

**Comment by starkos** [comment]
Sorry, no!

**Comment by sp-rafael-lecina** [comment]
Don't actually know why CI failed on this and worked on this other one: https://github.com/premake/premake-core/pull/1491
Didn´t have much info when going to details

**Review by samsinsane — APPROVED** [review]

**Pull request merged**
