### PR TITLE
Upgrade docusaurus version to beta.6

### PR DESCRIPTION
**Pull request by KyrietS**
**What does this PR do?**

Upgrade Docusaurus from alpha.70 to beta.6. I'd like to try a new Docusaurus' feature for sidebars auto-generation at some point in the future. This PR is my first step towards it.

**How does this PR change Premake's behavior?**

From Docusaurus perspective there are 2 changes that had to be made:
* Every file prefixed with an underscore is ignored so I had to rename some files: `_OPTIONS.md`, `_OS.md` etc. I used `premake` prefix for them.
* A path `/docs/tags/` is reserved by Docusaurus. I had to use different URL for `tags.md`.

**Anything else we should know?**

Everything should work as before.

**Did you check all the boxes?**

- [x] Focus on a single fix or feature; remove any unrelated formatting or code changes
- [x] Add unit tests showing fix or feature works; all tests pass
- [x] Mention any [related issues](https://github.com/premake/premake-core/issues) (put `closes #XXXX` in comment to auto-close issue when PR is merged)
- [x] Follow our [coding conventions](https://github.com/premake/premake-core/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] Minimize the number of commits
- [x] Align [documentation](https://github.com/premake/premake-core/tree/master/website) to your changes

*You can now [support Premake on our OpenCollective](https://opencollective.com/premake). Your contributions help us spend more time responding to requests like these!*

### CODE REVIEW

**Review by nickclark2016 — APPROVED** [review]
I'm happy to have us move out an alpha dependency.  +1

**Comment by KyrietS** [comment]
Yup, Docusaurus was in alpha for quite a long time, and now they announced that they are going to deprecate v1, so beta.6 is the best we can have now :-)

I also asked them how to prevent Docusaurus from reserving a `docs/tags` path (https://github.com/facebook/docusaurus/discussions/5542) and they were kind enough to immediately create PR and add this feature 😄 So hopefully my hack won't be necessary in beta.7.

**Comment by nickclark2016** [comment]
Should we wait for beta.7 then?

**Comment by KyrietS** [comment]
Nah, it's not that important. I'll merge it for now

**Pull request merged**
