### PR TITLE
Updated LICENSE.txt copyright year

### LINKED ISSUE #1833: Copyright year
Not really an issue just some quick help. Updated copyright year
[License.txt](https://github.com/premake/premake-core/files/8191497/License.txt)

### PR DESCRIPTION
**Pull request by nickclark2016**
**What does this PR do?**

Updates copyright year in LICENSE.txt from 2019 to 2022.

**How does this PR change Premake's behavior?**

No code changes.

**Anything else we should know?**

Closes #1833 

**Did you check all the boxes?**

- [x] Focus on a single fix or feature; remove any unrelated formatting or code changes
- [x] Add unit tests showing fix or feature works; all tests pass
- [x] Mention any [related issues](https://github.com/premake/premake-core/issues) (put `closes #XXXX` in comment to auto-close issue when PR is merged)
- [x] Follow our [coding conventions](https://github.com/premake/premake-core/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] Minimize the number of commits
- [x] Align [documentation](https://github.com/premake/premake-core/tree/master/website) to your changes

*You can now [support Premake on our OpenCollective](https://opencollective.com/premake). Your contributions help us spend more time responding to requests like these!*

### CODE REVIEW

**Comment by nickclark2016** [comment]
Just a thought, but moving forward, why don't we add an item to the checklist where if we touch a file, we update the copyright year?

**Comment by KyrietS** [comment]
> Just a thought, but moving forward, why don't we add an item to the checklist where if we touch a file, we update the copyright year? That's a practice that I do where I work, and it works out better than fixing it all at once before a SW delivery.

I'm not a big fan of having copyright clause in every single source file but your idea is not bad. However, I think the process of checking whether someone has updated the copyright date in the file that was touched could be somehow automated (and added to the pipeline).

**Review by KyrietS — APPROVED** [review]

**Comment by nickclark2016** [comment]
> > Just a thought, but moving forward, why don't we add an item to the checklist where if we touch a file, we update the copyright year? That's a practice that I do where I work, and it works out better than fixing it all at once before a SW delivery.
> 
> I'm not a big fan of having copyright clause in every single source file but your idea is not bad. However, I think the process of checking whether someone has updated the copyright date in the file that was touched could be somehow automated (and added to the pipeline).

Definitely could be added to the pipeline, I'm just not 100% sure how to do it.  Couldn't find a GitHub CI action in a cursory search.  Maybe a simple python or bash script to check in it's own runner and fail out if the copyright of the file touched wasn't updated?

**Comment by KyrietS** [comment]
I don't know how to do it. I was just thinking 😁

**Pull request merged**
