### PR TITLE
E2K: fixed build by MCST lcc compiler

### PR DESCRIPTION
**Pull request by r-a-sattarov**
**What does this PR do?**

- fixed build by MCST lcc compiler on MCST Elbrus 2000 architecture when using Curl
- strip UTF-8 BOM of file curl_utils.c for compability with MCST lcc compiler < 1.24

**How does this PR change Premake's behavior?**

This PR doesn't change Premake's behaviour to the end user.

**Anything else we should know?**

e2k (Elbrus 2000) - this is VLIW/EPIC architecture, like Intel Itanium architecture.

About this architecture:
- https://en.wikipedia.org/wiki/Elbrus_2000

**Did you check all the boxes?**

- [x] Focus on a single fix or feature; remove any unrelated formatting or code changes
- [ ] Add unit tests showing fix or feature works; all tests pass
- [ ] Mention any [related issues](https://github.com/premake/premake-core/issues) (put `closes #XXXX` in comment to auto-close issue when PR is merged)
- [ ] Follow our [coding conventions]([https://github.com/premake/premake-core/blob/master/CONTRIBUTING.md#coding-conventions](https://github.com/premake/premake-core/blob/master/CONTRIBUTING.md#coding-conventions))
- [x] Minimize the number of commits

*You can now [support Premake on our OpenCollective](https://opencollective.com/premake). Your contributions help us spend more time responding to requests like these!*

### CODE REVIEW

**Comment by r-a-sattarov** [comment]
My changes were accepted in the main branch of Curl.

curl/curl@8063c32

**Comment by starkos** [comment]
Seems to make more sense to just grab the new curl? I don't recall exactly what hoops we need to jump through when we do that though…

**Comment by r-a-sattarov** [comment]
There are differences in file structure between these versions of Curl (for example, curlbuild.h in the old version and system.h in the new version seem similar to each other).

But in any case, please remove BOM (Byte Order Mark) from src/host/curl_utils.c file. MCST lcc compiler version < 1.24 does not understand BOM.

**Comment by starkos** [comment]
Okay, guess it makes sense to get this merged now then. Thanks for the contribution!

**Pull request merged**
