### PR TITLE
Xcode embed libraries

### PR DESCRIPTION
**Pull request by nickgravelyn**
**What does this PR do?**

Provides a mechanism to specify `dylib`s and `framework`s to use Xcode's "Embed Libraries" functionality to optionally or embed & sign libraries. Trying to address #1518.

**How does this PR change Premake's behavior?**

1. Xcode projects now support specifying `.dylib` extensions in `links`. These can be relative or absolute paths but the libraries end up getting treated like `.framework`s. That is, they are added to the Frameworks build phase and show up in the Frameworks group rather than just being added as additional linker flags. This was a prerequisite for `dylib`s to get embedded.
2. A new `xcodeembedlibraries` command was added that allows a project to specify the list of libraries to embed in a map, mapping the name of the library (not the path) to a string of either `"embed"` or `"embed-and-sign"`. 

**Anything else we should know?**

While this functionally achieves the goals as far as I can tell, I'm not married to the implementation or interface so I'm open to suggestions there. The `xcodeembedlibraries` feels weird particularly because strings aren't great for this. I thought about just having the right hand side be true/false but that felt too opaque as to what it was doing. I also considered separate commands as discussed in #1518 but ultimately it felt nicer to have a single command since it's controlling a single list in Xcode.

I've written automated tests and verified this works on my own project (which embeds and signs a local `dylib`) but it probably needs more testing around the edges.

I left this as two commits so that it's easier to review the two changes described above. I'm happy to rebase/squash it later if desired for merging.

**Did you check all the boxes?**

- [X] Focus on a single fix or feature; remove any unrelated formatting or code changes
- [X] Add unit tests showing fix or feature works; all tests pass
- [X] Mention any [related issues](https://github.com/premake/premake-core/issues) (put `closes #XXXX` in comment to auto-close issue when PR is merged)
- [X] Follow our [coding conventions](https://github.com/premake/premake-core/blob/master/CONTRIBUTING.md#coding-conventions)
- [X] Minimize the number of commits

*You can now [support Premake on our OpenCollective](https://opencollective.com/premake). Your contributions help us spend more time responding to requests like these!*

### CODE REVIEW

**Comment by thomashope** [comment]
Hi, nice work on the PR.

Read through the changes, the first commit looks good to me. Wasn't sure about the second one so I recreated your changes on my end and found a few issues in the process:

1) Embedded items should have have an additional entry in the `PBXBuildFile section`, even if they are not code signed. 

2) Frameworks should have `RemoveHeadersOnCopy` attribute set like so `		0DAEAB24FB163DD698103164 /* SDL2.framework in Embed Frameworks */ = {isa = PBXBuildFile; fileRef = 7D41A17F89CC53F104B11FBF /* SDL2.framework */; settings = {ATTRIBUTES = (RemoveHeadersOnCopy, ); }; };`. This attribute seems to do pretty much as described, if you look inside framework copied into the built .app you will see the Headers folder has been removed.

3) Pretty sure we need to add `LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/../Frameworks";` so that the executable finds and uses the correct framework placed inside the app bundle. I am guessing what happened on your end was the files appeared to be copied to the correct location but the executable selected you system installed libraries? You should be able to check that by moving/renaming your system libraries and see if your app crashes.

I have done all this testing using .frameworks because that's what I need it for. You can see that reflected in my code where it says 'Embed Frameworks' wheras yours says 'Embed Libraries'. Would be interested to know what xcode generates when you mix the two and if there are any additional cases to handle.

Are you able to you share your project folder structure / premake5.lua using .dylibs so I can test it out on my end?

[Here's the link](https://github.com/thomashope/premake-core/commit/5b570f32ae4cd1f6a37bb76a12307d99ec5ade73) to my commit sans tests if you want to take a look. I went for having separate `xcodeembedwithoutsigning` and `xcodeembedandsign` just to see how it would pan out.

Bearing in mind this is all stuff i've been figuring out from my own experimentation/looking at your code/and fiddling with the xcode project, so I may be wrong!

**Comment by nickgravelyn** [comment]
Hey @thomashope. Thanks for taking a peek.

1. Oh yes good catch. I'll fix that up. I didn't have a use case for not signing so I didn't catch that it was missing.
2. That's a good point and seems reasonable. I don't use frameworks much so I forget about the embedded headers. IIRC Xcode lets you specify whether or not to remove headers but it seems reasonable to default to doing so and someone can come patch in a way to disable that if there's some reason they want to bloat their app bundle with a bundle of header files.
3. I don't think that should be done automatically. Sometimes libraries will already be built with that path into them, but for others I think the project should specify it themselves using `xcodebuildsettings { ["LD_RUNPATH_SEARCH_PATHS"] = "@executable_path/../Frameworks" }`.

I don't think there are any concerns with mixing the two. Xcode just names it based on what you add first, I believe. They're all linked and copied to the same place in the end.

**Comment by nickgravelyn** [comment]
Ok I've addressed the first two points (did a rebase and kept it at two commits). You can see the test cases here: https://github.com/premake/premake-core/pull/1524/files#diff-06a55edcdb18495d6fe7e42f832b512dR122-R153

**Comment by thomashope** [comment]
So I built your code and ran it on my project, and it works!

For reference here is what I had to do to my premake5.lua to get local frameworks correctly embedded into my app:

```lua
links {
    "third_party/sdl2/macos/SDL2.framework",
}

sysincludedirs {
    "third_party/sdl2/macos/SDL2.framework/Headers",
}

frameworkdirs {
    "third_party/sdl2/macos/",
}

xcodeembedlibraries {
    ["SDL2.framework"] = "embed-and-sign"
}

xcodebuildsettings {
    ["LD_RUNPATH_SEARCH_PATHS"] = "$(inherited) @executable_path/../Frameworks",
}
```

It's a fair bit of config for one framework and I think the user experience here can be improved, but this PR is a step in the right direction so it's a 👍 from me.

**Comment by nickgravelyn** [comment]
That’s great to hear. I realized I need to do some more testing for embedding projects as well as loose file. Once that’s done I think the big question will just be about the interface to make sure it seems reasonable.

**Comment by nickgravelyn** [comment]
Ok I've fixed things up so project references can also be marked to embed or embed & sign. Instead of using the file name it's the name of the project. This felt better since it matches with what users specify in `links`. I wrote some automated tests in the dependency test file but I also did a quick manual test and it worked in Xcode.

At this point things are functional for relative `dylib`/`framework` references as well as `SharedLib` project references. I'd be fine with this `xcodeembedlibraries` interface but I'm also happy to adjust it if someone has a more user-friendly idea of how we can expose these options.

**Comment by starkos** [comment]
The not a fan of the table syntax for this one. I'm not a fan of the table syntax in general and use it only under duress, but this one really doesn't need it. I would much prefer that it use separate APIs instead.

```lua
links { "SDL" }
embed { "SDL" }
embedAndSign { "SDL" }
```

**Comment by nickgravelyn** [comment]
I deleted my fork at some point so to continue this PR I had to re-fork and make a new PR. I've applied the API changes requested in #1619. Going to close this one out.

**Pull request closed without merging**
