### PR TITLE
Revert "Improve error message of `include`

### PR DESCRIPTION
**Pull request by nickclark2016**
Reverts premake/premake-core#2066

Breaks includes.

### CODE REVIEW

**Comment by nickclark2016** [comment]
@Jarod42 can you verify that this branch works?

**Comment by Jarod42** [comment]
Ok for me.

**Comment by nickclark2016** [comment]
As soon as I get an approving review, I'll merge and delete branch.

**Comment by Jarod42** [comment]
Just created #2122 which fixes the issue.

Seeing issue was more tricky that what I though:
- premake in original directory was ok, but moving the file elsewhere makes the error appears.

That is for that I didn't see the issue before. (I changed recently my "config" after a reinstall).

**Comment by nickclark2016** [comment]
> Just created #2122 which fixes the issue.
> 
> Seeing issue was more tricky that what I though:
> 
> * premake in original directory was ok, but moving the file elsewhere makes the error appears.
> 
> That is for that I didn't see the issue before. (I changed recently my "config" after a reinstall).

Is this based on master? If so, I'll go ahead and close this move forward with yours.

**Comment by Jarod42** [comment]
Yes was based on master.

**Pull request closed without merging**
