### PR TITLE
Readme overhaul

### PR DESCRIPTION
**Pull request by Lusito**
Made the readme.md more informative and newcomer friendly.

### CODE REVIEW

**Comment by starkos** [comment]
Nice, thanks! Two little things:

* Can the help section include the StackOverflow link? See [Getting Help](https://github.com/premake/premake-core/wiki/Getting_Help) to see what I mean. I'd really like to push questions about using Premake over to SO, and keep the discussion list focused on actually building or customizing Premake itself.

* Can we drop the mention of BUILD.txt and send them to [Building Premake](https://github.com/premake/premake-core/wiki/Building-Premake) instead? These two keep falling out of sync and I think I'd like to drop BUILD.txt entirely.

Otherwise great! I will follow up your other points on the issue tracker.

**Comment by Lusito** [comment]
done

**Comment by TurkeyMan** [comment]
Really nice!
I'd love to see that link to the tests directory replaced by a wiki article describing how to run and author new unit tests. Can you point at a placeholder and we can populate the article?

**Comment by Lusito** [comment]
done

**Comment by starkos** [comment]
Thanks!

**Pull request merged**
