### PR TITLE
Add GitHub Action workflow for website deployment

### PR DESCRIPTION
**Pull request by KyrietS**
**What does this PR do?**

Added `website.yml` with CI jobs for tests and deployment of the website.

**How does this PR change Premake's repo behavior?**

* Every push and pull request that affects anything in `website/**` will trigger website build (to make sure no errors were introduced)
* Every **push to master** that affects anything in `website/**` will trigger website deployment. It means that the website will be built and pushed to master branch of premake.github.io. Repo premake.github.io will not grow in size because no history will be preserved between deployments.

**Anything else we should know?**

You might ask: "Where is premake.github.io repo specifieed as deployment target?". It's inside `docusaurus.config.js`.

* `organizationName` is GitHub account name: github.com/**premake**/premake.github.io
* `projectName` is target repository: github.com/premake/**premake.github.io**

It's weird mapping in my opinion but this is how `docusaurus deploy` command works.

**Did you check all the boxes?**

- [x] Focus on a single fix or feature; remove any unrelated formatting or code changes
- [ ] ~~Add unit tests showing fix or feature works; all tests pass~~ *I tested this gh-action on my fork with merges and pull requests*
- [x] Mention any [related issues](https://github.com/premake/premake-core/issues) (put `closes #XXXX` in comment to auto-close issue when PR is merged)
- [x] Follow our [coding conventions](https://github.com/premake/premake-core/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] Minimize the number of commits

*You can now [support Premake on our OpenCollective](https://opencollective.com/premake). Your contributions help us spend more time responding to requests like these!*

**Instructions for @starkos before merging this commit**

1. Generate public and private key.
2. Go to [premake.github.io](https://github.com/premake/premake.github.io) repository -> settings -> Deploy keys -> Add deploy key. Name it anything you want and paste **public key** in there. **Check Allow write access**.
3. Go to premake-core repository -> settings -> Secrets -> New repository secret. Name it "WEBSITE_DEPLOY_KEY" and paste **private key** in there.
4. Ready to go.

#1547

### CODE REVIEW

**Review by starkos — CHANGES_REQUESTED** [review]
I'll get that key set up. Can you add the relevant info from this PR to `website/README.md` so we have it for future reference? Thanks!

**Comment by KyrietS** [comment]
You mean my `docusaurus.config.js` explanation part? I don't think those two fields that I mention there are ever going to be changed so documenting them in README seems verbose to me.

**Comment by starkos** [comment]
> I don't think those two fields that I mention there are ever going to be changed

…until they need to be, and and we have to hunt around to find them. Please document those, the deployment action triggers( "Every push and pull request") and the need for and location of the deployment keys. Thanks!

Don't worry, we still have lots of space in our README quota :)

**Comment by starkos** [comment]
I've set up the deployment key. Once #1602 lands I think we have enough in place to go live!

**Review by starkos — APPROVED** [review]
#1602 has landed, approving this one to merge.

**Comment by KyrietS** [comment]
I added some information to our README file. You can merge it when you are ready. I'd like you to do it so you can track the process of deployment and react if something unexpected happens (it won't).

**Pull request merged**
