### PR TITLE
Add C++17 support for Visual Studio 2017.

### PR DESCRIPTION
**Pull request by manxorist**
This also adds support for 'cppdialect "C++latest"'.

### CODE REVIEW

**Comment by manxorist** [comment]
This pull request is based on discussion in #1009.

**Comment by pdoane** [comment]
There are two directions that can work here:

  1. Use the specific Visual Studio version (e.g. 15.6) in the action.  VS2017 is no longer enough information to figure out how to map some options and only supporting the latest release isn't practical for how VS2017 is being developed.
  2. Use options that directly map to Visual Studio usage (in this case C++latest).

More details of this were discussed on #1009.

**Comment by manxorist** [comment]
> Use the specific Visual Studio version (e.g. 15.6) in the action. VS2017 is no longer enough information to figure out how to map some options and only supporting the latest release isn't practical for how VS2017 is being developed.

It never was. As already mentioned, minor versions of Visual Studio did add features also in earlier versions.

> Use options that directly map to Visual Studio usage (in this case C++latest).

Which is precisely what I have implemented in this pull request.

> More details of this were discussed on #1009.

I just **need** C++17 support, and I will happily change the pull request to whatever minimal solution is desired. In #1009 it was requested to add `"C++latest"` (which I think totally makes sense to have), which I did.

**Comment by pdoane** [comment]
Is there anything left to go over here? We talked through this a bit on the previous PR and this is implementing the decision made there.

**Pull request merged**
