### PR TITLE
support framework folders and bundles in gcc for mac.

### PR DESCRIPTION
**Pull request by tvandijck**
This allows you to link against frameworks on mac, and to create .bundle files.

### CODE REVIEW

**Comment by starkos** [comment]
I think this might be better as a new kind ("Framework", maybe?) than a flag. The tight coupling with the SharedLib flag feels wrong. Thoughts?

**Comment by tvandijck** [comment]
that's an idea...

**Comment by tvandijck** [comment]
Actually to get back on that, according to the xcode documentation there is several types of bundles...

application bundles, framework bundles and loadable bundles....
so the fact that we want a bundle, is not really a "kind".

- an application bundle is an "application" kind + bundle flag.
- a framework bundle is a "static lib" kind + bundle flag.
- a loadable bundle is a "dynamic lib" kind + bundle flag.

**Comment by starkos** [comment]
A WindowedApp on Mac OS X creates an application bundle, so that case is already covered. Frameworks are very common and I think it would be worth having a specific kind for them. Bundles aren't used nearly as often, and are basically an application with (optionally) a different entry point, so perhaps we treat them like that?

Anyway, getting back to this specific change, I still think the introduction of a "Framework" kind is the way to go.

**Comment by tvandijck** [comment]
OK, what about "dynamic libs" then? which is actually the case we're using it for..

"Battle.net.bundle"

**Comment by starkos** [comment]
Oh, yes, true. I guess I still prefer a kind of "Bundle" over "SharedLib" + a flag. For incompatible configurations (not OS X) we should raise an error during validation, for now at least. What do you think?

**Comment by tvandijck** [comment]
OK, that works for me... I'll have to refactor this on our end then, and see where that takes us... Let me talk it over with our mac team, see what they have to say, since they are the guys writing the new xcode 6 action.

**Pull request closed without merging**
